from __future__ import annotations

from copy import deepcopy
from datetime import datetime, timezone
import os


DEFAULT_SETTINGS = {
    "logRetention": 1500,
    "bodyInspectionLimit": 131072,
    "panel": {
        "httpsEnabled": False,
        "certificateId": "",
        "publicUrl": "",
        "faviconUrl": "",
        "logoUrl": "",
        "sessionHours": 12,
    },
    "rateLimit": {
        "enabled": True,
        "windowMs": 60000,
        "max": 120,
    },
    "applicationDefaults": {
        "proxy": {
            "forceHttps": False,
            "hsts": False,
            "hstsMaxAge": 15768000,
            "gzip": True,
            "brotli": False,
            "http2": True,
            "resetXff": True,
            "modifyHostHeader": True,
            "forwardedHeaders": True,
            "hostHeader": "$http_host",
            "xForwardedProto": "$scheme",
            "xForwardedHost": "$http_host",
            "proxySslServerName": True,
        },
        "modSecurity": {
            "enabled": True,
            "mode": "on",
            "ruleset": "comodo",
            "requestBodyLimit": 13107200,
        },
    },
    "challengePage": {
        "brandName": "FreeWAF",
        "title": "Security check",
        "message": "We are verifying your browser before continuing.",
        "logoUrl": "",
        "supportUrl": "",
        "primaryColor": "#18a69a",
        "backgroundColor": "#f5f7f8",
        "textColor": "#17202a",
        "tokenTtlMinutes": 30,
        "waitSeconds": 5,
        "powDifficulty": 16,
    },
    "blockPageTitle": "Request blocked",
    "blockSupportIdPrefix": "SFL",
}

DEFAULT_BOT_LOGIN_PATH_PATTERNS = [
    r"^/wp-login\.php(?:\?|$)",
    r"^/wp-admin/?(?:\?|$)",
    r"^/(?:admin|administrator)(?:/login)?/?(?:\?|$)",
    r"^/(?:login|user/login|account/login)(?:/|\?|$)",
    r"^/clientarea\.php(?:\?|$)",
    r"^/cart\.php(?:\?[^#]*\ba=login\b|$)",
    r"^/index\.php/(?:login|admin)(?:/|\?|$)",
    r"^/admin/index\.php(?:\?|$)",
]

DEFAULT_BOT_RATE_CHALLENGE = {
    "enabled": False,
    "windowSeconds": 10,
    "challengeCount": 300,
    "blockCount": 700,
    "blockMinutes": 30,
}

VERIFIED_BOT_PROVIDERS = {
    "google": {
        "id": "ipgroup-verified-googlebot",
        "name": "Verified Google Common Crawlers",
        "description": "Official Google common crawler CIDR ranges. Managed and synced daily by FreeWAF.",
        "referenceUrl": "https://developers.google.com/static/crawling/ipranges/common-crawlers.json",
        "userAgentPattern": r"(?:Googlebot|Google-InspectionTool|GoogleOther|Storebot-Google|Google-CloudVertexBot)",
    },
    "bing": {
        "id": "ipgroup-verified-bingbot",
        "name": "Verified Bingbot",
        "description": "Official Bingbot CIDR ranges. Managed and synced daily by FreeWAF.",
        "referenceUrl": "https://www.bing.com/toolbox/bingbot.json",
        "userAgentPattern": r"(?:bingbot|adidxbot|MicrosoftPreview)",
    },
}


VERIFIED_AI_BOT_PROVIDERS = {
    "openai_search": {
        "id": "ipgroup-verified-openai-searchbot",
        "name": "Verified OpenAI SearchBot",
        "description": "Official OAI-SearchBot CIDR ranges. Managed and synced daily by FreeWAF.",
        "referenceUrl": "https://openai.com/searchbot.json",
        "userAgentPattern": r"(?:OAI-SearchBot)",
    },
    "openai_user": {
        "id": "ipgroup-verified-chatgpt-user",
        "name": "Verified ChatGPT User",
        "description": "Official ChatGPT-User CIDR ranges. Managed and synced daily by FreeWAF.",
        "referenceUrl": "https://openai.com/chatgpt-user.json",
        "userAgentPattern": r"(?:ChatGPT-User)",
    },
    "openai_gptbot": {
        "id": "ipgroup-verified-gptbot",
        "name": "Verified GPTBot",
        "description": "Official GPTBot CIDR ranges. Managed and synced daily by FreeWAF.",
        "referenceUrl": "https://openai.com/gptbot.json",
        "userAgentPattern": r"(?:GPTBot)",
    },
    "anthropic_search": {
        "id": "ipgroup-verified-claude-searchbot",
        "name": "Verified Claude SearchBot",
        "description": "Official Anthropic outbound crawler range for Claude-SearchBot. Managed by FreeWAF.",
        "referenceUrl": "",
        "items": ["160.79.104.0/21"],
        "userAgentPattern": r"(?:Claude-SearchBot)",
    },
    "anthropic_user": {
        "id": "ipgroup-verified-claude-user",
        "name": "Verified Claude User",
        "description": "Official Anthropic outbound user-fetch range for Claude-User. Managed by FreeWAF.",
        "referenceUrl": "",
        "items": ["160.79.104.0/21"],
        "userAgentPattern": r"(?:Claude-User)",
    },
    "anthropic_claudebot": {
        "id": "ipgroup-verified-claudebot",
        "name": "Verified ClaudeBot",
        "description": "Official Anthropic outbound crawler range for ClaudeBot. Managed by FreeWAF.",
        "referenceUrl": "",
        "items": ["160.79.104.0/21"],
        "userAgentPattern": r"(?:ClaudeBot)",
    },
    "perplexity_bot": {
        "id": "ipgroup-verified-perplexitybot",
        "name": "Verified PerplexityBot",
        "description": "Official PerplexityBot CIDR ranges. Managed and synced daily by FreeWAF.",
        "referenceUrl": "https://www.perplexity.com/perplexitybot.json",
        "userAgentPattern": r"(?:PerplexityBot)",
    },
    "perplexity_user": {
        "id": "ipgroup-verified-perplexity-user",
        "name": "Verified Perplexity User",
        "description": "Official Perplexity user-fetch CIDR ranges. Managed and synced daily by FreeWAF.",
        "referenceUrl": "https://www.perplexity.com/perplexity-user.json",
        "userAgentPattern": r"(?:Perplexity-User)",
    },
}


def managed_verified_bot_providers() -> dict:
    return {**VERIFIED_BOT_PROVIDERS, **VERIFIED_AI_BOT_PROVIDERS}


def challenge_secret() -> str:
    return os.environ.get("FREEWAF_CHALLENGE_SECRET", "").strip() or "freewaf-development-challenge-secret"


BUILTIN_RULES = [
    {
        "id": "builtin-sqli-basic",
        "name": "SQL injection probes",
        "description": "Common tautology, UNION, delay, and schema probing payloads.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "all",
        "pattern": r"(?:\bunion\b\s+\bselect\b|\bor\b\s+1\s*=\s*1|\band\b\s+1\s*=\s*1|sleep\s*\(|benchmark\s*\(|information_schema|--\s|/\*)",
        "action": "block",
        "severity": "critical",
    },
    {
        "id": "builtin-xss-basic",
        "name": "Cross-site scripting probes",
        "description": "Script tags, JavaScript URLs, event handlers, and cookie theft strings.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "all",
        "pattern": r"(?:<\s*script\b|javascript\s*:|onerror\s*=|onload\s*=|<\s*iframe\b|document\.cookie)",
        "action": "block",
        "severity": "high",
    },
    {
        "id": "builtin-path-traversal",
        "name": "Path traversal and local file reads",
        "description": "Traversal sequences and common sensitive local files.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "all",
        "pattern": r"(?:\.\./|\.\.\\|/etc/passwd|boot\.ini|proc/self/environ)",
        "action": "block",
        "severity": "high",
    },
    {
        "id": "builtin-command-injection",
        "name": "Command injection markers",
        "description": "Shell metacharacters followed by common command execution tools.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "all",
        "pattern": r"(?:;\s*(?:cat|curl|wget|bash|sh|powershell)\b|\|\s*(?:cat|curl|wget|bash|sh)\b|\$\(|`)",
        "action": "block",
        "severity": "critical",
    },
    {
        "id": "builtin-scanner-agent",
        "name": "Scanner user agents",
        "description": "Common vulnerability scanners and mass HTTP clients.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "headers",
        "pattern": r"(?:sqlmap|nikto|acunetix|nessus|masscan|nmap|zgrab|go-http-client)",
        "action": "block",
        "severity": "medium",
    },
    {
        "id": "builtin-sensitive-file",
        "name": "Sensitive file discovery",
        "description": "Requests for common secrets, source folders, and backup archives.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "url",
        "pattern": r"(?:/\.env\b|/\.git/|wp-config\.php|composer\.json|id_rsa|backup\.(?:zip|sql|tar))",
        "action": "block",
        "severity": "high",
    },
    {
        "id": "builtin-dangerous-methods",
        "name": "Dangerous HTTP methods",
        "description": "Methods that are usually unnecessary for public web applications.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "method",
        "pattern": r"^(?:TRACE|TRACK)$",
        "action": "block",
        "severity": "medium",
    },
    {
        "id": "builtin-wordpress-sensitive-files",
        "name": "[WordPress] Sensitive application files",
        "description": "Blocks direct access to WordPress config, install/upgrade scripts, debug logs, and PHP payloads in uploads.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "url",
        "pattern": r"(?:/wp-config\.php(?:[.~]|$|\?)|/wp-content/(?:debug\.log|uploads/[^?]*\.(?:php[0-9]?|phtml|phar))|/wp-admin/(?:install|setup-config|upgrade)\.php|/(?:readme|license)\.txt(?:$|\?))",
        "action": "block",
        "severity": "high",
    },
    {
        "id": "builtin-wordpress-enumeration",
        "name": "[WordPress] User enumeration probes",
        "description": "Blocks common author and REST API user enumeration scans.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "url",
        "pattern": r"(?:[?&]author=\d+\b|/(?:index\.php/)?wp-json/wp/v2/users\b)",
        "action": "block",
        "severity": "medium",
    },
    {
        "id": "builtin-whmcs-sensitive-paths",
        "name": "[WHMCS] Sensitive files and directories",
        "description": "Blocks direct access to WHMCS configuration, installer, crons, compiled templates, attachments, downloads, and vendor folders.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "url",
        "pattern": r"(?:/(?:configuration\.php|install/|crons/|templates_c/|attachments/|downloads/|vendor/)(?:$|[/?])|/vendor/composer/(?:installed|autoload_(?:real|static))\.php)",
        "action": "block",
        "severity": "high",
    },
    {
        "id": "builtin-laravel-sensitive-files",
        "name": "[Laravel] Env, logs, and framework internals",
        "description": "Blocks exposed Laravel environment files, logs, artisan/server scripts, storage, cache, vendor, Telescope, Horizon, and Ignition endpoints.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "url",
        "pattern": r"(?:/\.env(?:$|\?|/)|/storage/logs/laravel(?:-\d{4}-\d{2}-\d{2})?\.log|/(?:artisan|server\.php|composer\.(?:json|lock))(?:$|\?)|^/vendor(?:/|$)|/(?:bootstrap/cache|storage/framework)(?:/|$)|/_ignition/(?:execute-solution|health-check)|/(?:telescope|horizon)(?:/|$))",
        "action": "block",
        "severity": "critical",
    },
    {
        "id": "builtin-codeigniter-sensitive-paths",
        "name": "[CodeIgniter] Protected framework paths",
        "description": "Blocks common CodeIgniter application, system, writable logs/cache/session paths and traversal probes.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "url",
        "pattern": r"(?:/application/(?:config|logs|cache|sessions|core|helpers|libraries)/|/system/(?:core|database|helpers|libraries)/|/writable/(?:logs|cache|session|uploads)/|/\.env(?:$|\?)|/index\.php/\.\./)",
        "action": "block",
        "severity": "high",
    },
    {
        "id": "builtin-hostbill-sensitive-paths",
        "name": "[HostBill] Sensitive files and directories",
        "description": "Blocks direct access to HostBill config, install/upgrade, vendor, compiled templates, attachments, downloads, and backup-like module files.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "url",
        "pattern": r"(?:/(?:hb_config\.php|includes/config\.php|install/|upgrade/|vendor/|templates_c/|attachments/|downloads/)(?:$|[/?])|/includes/(?:libs|modules|hooks)/[^?]*\.(?:bak|old|save|swp|sql)(?:$|\?))",
        "action": "block",
        "severity": "high",
    },
    {
        "id": "builtin-php-vendor-test-exposure",
        "name": "[PHP] Vendor and PHPUnit exposure",
        "description": "Blocks package-manager metadata and PHPUnit/vendor paths commonly probed across PHP applications.",
        "builtin": True,
        "enabled": True,
        "siteId": "*",
        "matcher": "regex",
        "target": "url",
        "pattern": r"(?:/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin\.php|/vendor/(?:phpunit|composer)(?:/|$)|/composer\.(?:json|lock)(?:$|\?))",
        "action": "block",
        "severity": "critical",
    },
]


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def create_default_state(now: str | None = None) -> dict:
    timestamp = now or utc_now()
    return {
        "version": 1,
        "settings": deepcopy(DEFAULT_SETTINGS),
        "sites": [
            {
                "id": "site-demo",
                "name": "Demo origin",
                "applicationType": "reverse_proxy",
                "hostnames": ["localhost", "127.0.0.1"],
                "origin": "http://127.0.0.1:9090",
                "upstreams": ["http://127.0.0.1:9090"],
                "ports": ["8080"],
                "listen": 8080,
                "redirectStatusCode": 301,
                "tls": {
                    "enabled": False,
                    "certificateId": "",
                    "redirectHttp": False,
                    "httpListen": 80,
                    "http2": True,
                },
                "proxy": {
                    "forceHttps": False,
                    "redirectStatusCode": 301,
                    "hsts": False,
                    "hstsMaxAge": "15768000",
                    "gzip": True,
                    "brotli": False,
                    "http2": True,
                    "ipv6": False,
                    "resetXff": True,
                    "defaultServer": False,
                    "strictHost": False,
                    "accessLog": True,
                    "modifyHostHeader": True,
                    "forwardedHeaders": True,
                    "hostHeader": "$http_host",
                    "xForwardedProto": "$scheme",
                    "xForwardedHost": "$http_host",
                    "proxySslServerName": True,
                },
                "modSecurity": {
                    "enabled": True,
                    "mode": "on",
                    "ruleset": "comodo",
                    "requestBodyLimit": 13107200,
                },
                "redirect": {
                    "statusCode": 301,
                    "address": "",
                },
                "static": {
                    "root": "",
                },
                "acl": {
                    "enabled": True,
                    "rateLimitMode": "custom",
                    "waitingRoom": False,
                    "accessLimit": {
                        "enabled": True,
                        "period": 10,
                        "count": 200,
                        "blockCount": 500,
                        "action": "challenge_v1",
                        "blockMin": 60,
                    },
                    "attackLimit": {
                        "enabled": True,
                        "period": 60,
                        "count": 10,
                        "action": "block",
                        "blockMin": 30,
                    },
                    "errorLimit": {
                        "enabled": True,
                        "period": 10,
                        "count": 10,
                        "action": "block",
                        "blockMin": 30,
                        "statusCodes": ["403", "404"],
                    },
                },
                "features": {
                    "httpFlood": True,
                    "botProtection": True,
                    "geoBlock": False,
                },
                "botProtection": {
                    "enabled": True,
                    "antiBotChallenge": True,
                    "verifiedSearchBots": {
                        "enabled": True,
                        "bypassChallenge": True,
                        "bypassRateLimit": True,
                    },
                    "verifiedAIBots": {
                        "enabled": False,
                        "allowedProviders": [],
                        "bypassChallenge": True,
                        "bypassRateLimit": True,
                    },
                    "loginChallenge": {
                        "enabled": True,
                        "pathPatterns": deepcopy(DEFAULT_BOT_LOGIN_PATH_PATTERNS),
                    },
                    "rateChallenge": deepcopy(DEFAULT_BOT_RATE_CHALLENGE),
                    "dynamicProtection": {
                        "enabled": False,
                        "html": False,
                        "js": False,
                        "watermark": False,
                    },
                    "antiReplay": {
                        "enabled": False,
                    },
                },
                "geoBlock": {
                    "enabled": False,
                    "countries": [],
                    "action": "block",
                },
                "mode": "block",
                "enabled": True,
                "createdAt": timestamp,
                "updatedAt": timestamp,
            }
        ],
        "rules": [
            {
                **deepcopy(rule),
                "createdAt": timestamp,
                "updatedAt": timestamp,
            }
            for rule in BUILTIN_RULES
        ],
        "certificates": [],
        "ipGroups": [
            {
                "id": "ipgroup-local",
                "name": "Local addresses",
                "description": "Loopback addresses useful for local testing.",
                "referenceUrl": "",
                "items": ["127.0.0.1/32", "::1/128"],
                "lastSyncedAt": "",
                "lastSyncStatus": "",
                "lastSyncMessage": "",
                "enabled": True,
                "createdAt": timestamp,
                "updatedAt": timestamp,
            },
            *[
                {
                    "id": provider["id"],
                    "name": provider["name"],
                    "description": provider["description"],
                    "referenceUrl": provider["referenceUrl"],
                    "items": deepcopy(provider.get("items", [])),
                    "lastSyncedAt": "",
                    "lastSyncStatus": "",
                    "lastSyncMessage": "",
                    "enabled": True,
                    "managed": True,
                    "provider": provider_name,
                    "createdAt": timestamp,
                    "updatedAt": timestamp,
                }
                for provider_name, provider in managed_verified_bot_providers().items()
            ],
        ],
        "accessRules": [],
        "users": [],
        "logs": [],
    }
