from __future__ import annotations

import os
import csv
import gzip
import ipaddress
import json
import re
import shlex
import subprocess
from pathlib import Path
from urllib.parse import urlparse

from .defaults import DEFAULT_BOT_LOGIN_PATH_PATTERNS, DEFAULT_BOT_RATE_CHALLENGE, VERIFIED_BOT_PROVIDERS, challenge_secret


NATIVE_TARGETS = {"all", "url", "headers", "method", "ip"}
BOT_RULE_IDS = {"builtin-scanner-agent"}
BOT_BLOCK_UA_PATTERN = (
    r"(?:sqlmap|nikto|acunetix|nessus|nuclei|wpscan|masscan|nmap|zgrab|gobuster|"
    r"dirbuster|ffuf|jaeles|zmeu|commix|havij|netsparker|openvas|arachni)"
)
GEO_CIDR_CACHE = {}


def nginx_output_file(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_OUTPUT_FILE", "./nginx/generated/freewaf.conf"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_site_config_dir(root_dir: Path) -> Path:
    configured = os.environ.get("NGINX_SITE_CONF_DIR", "").strip()
    if configured:
        path = Path(configured)
        return path if path.is_absolute() else root_dir / path
    return nginx_output_file(root_dir).parent / "sites"


def nginx_access_log_file(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_ACCESS_LOG", "./logs/freewaf_access.log"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_access_log_directive() -> str:
    configured = os.environ.get("NGINX_ACCESS_LOG", "./logs/freewaf_access.log")
    return configured.replace("\\", "/")


def nginx_site_log_dir(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_SITE_LOG_DIR", "./logs/freewaf"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_site_log_dir_directive() -> str:
    return os.environ.get("NGINX_SITE_LOG_DIR", "./logs/freewaf").replace("\\", "/").rstrip("/")


def nginx_site_access_log_directive(site: dict) -> str:
    return f"{nginx_site_log_dir_directive()}/accesslog_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def nginx_site_error_log_directive(site: dict) -> str:
    return f"{nginx_site_log_dir_directive()}/errorlog_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def generate_nginx_config(state: dict) -> str:
    blocks = generate_nginx_common_blocks(state)
    site_configs = render_domain_config_files(state)
    if not site_configs:
        blocks.append("# No enabled sites.")
    else:
        blocks.extend(site_configs.values())
    return "\n\n".join(blocks) + "\n"


def generate_nginx_common_blocks(state: dict) -> list[str]:
    enabled_sites = [site for site in state.get("sites", []) if site.get("enabled")]
    enabled_access_rules = [rule for rule in state.get("accessRules", []) if rule.get("enabled")]
    blocks = [
        "# Generated by FreeWAF. Do not edit by hand.",
        "# Include this file inside the nginx http {} context.",
        "",
        "map $request_uri $sfl_verdict {",
        "    default allow;",
        "}",
        "",
        "map $request_uri $sfl_reason {",
        "    default \"Allowed\";",
        "}",
        "",
        "log_format freewaf escape=json '{\"time\":\"$time_iso8601\",\"remote_addr\":\"$remote_addr\",\"host\":\"$host\",\"method\":\"$request_method\",\"uri\":\"$request_uri\",\"status\":$status,\"bytes\":$body_bytes_sent,\"request_time\":$request_time,\"upstream_status\":\"$upstream_status\",\"verdict\":\"$sfl_verdict\",\"reason\":\"$sfl_reason\",\"user_agent\":\"$http_user_agent\",\"referer\":\"$http_referer\"}';",
        "",
        "map $http_upgrade $sfl_connection_upgrade {",
        "    default upgrade;",
        "    '' close;",
        "}",
        "",
    ]

    verified_bot_maps = render_verified_bot_maps(state, enabled_sites)
    if verified_bot_maps:
        blocks.extend(verified_bot_maps)

    if any(site_bot_protection(site).get("antiBotChallenge") for site in enabled_sites):
        blocks.extend(render_bot_detection_maps())

    if any_uses_challenge(enabled_sites):
        blocks.extend(render_challenge_maps())

    bot_zones = render_bot_limit_zones(enabled_sites)
    if bot_zones:
        blocks.extend(bot_zones)

    rate_limit = state.get("settings", {}).get("rateLimit", {})
    uses_global_rate = any(
        site_features(site).get("httpFlood") and not active_acl_access_limit(site)
        for site in enabled_sites
    )
    if rate_limit.get("enabled") and uses_global_rate:
        blocks.extend(render_global_rate_limit_zones(rate_limit, any_verified_bot_rate_bypass(enabled_sites)))

    acl_zones = render_acl_limit_zones(enabled_sites)
    if acl_zones:
        blocks.extend(acl_zones)

    if (rate_limit.get("enabled") and uses_global_rate) or acl_zones or bot_zones:
        blocks.extend(["limit_req_status 429;", ""])

    geo_maps = render_geo_block_maps(enabled_sites)
    if geo_maps:
        blocks.extend(geo_maps)

    access_maps = render_access_maps(state, enabled_access_rules)
    if access_maps:
        blocks.extend(access_maps)
        blocks.append("")

    return blocks


def render_domain_config_files(state: dict) -> dict[str, str]:
    enabled_sites = [site for site in state.get("sites", []) if site.get("enabled")]
    certificates = {certificate["id"]: certificate for certificate in state.get("certificates", [])}
    configs = {}
    for site in enabled_sites:
        for hostname in site_hostnames(site):
            filename = domain_config_filename(site, hostname)
            configs[filename] = render_site_server(site, state, certificates, hostname)
    return configs


def write_nginx_config(root_dir: Path, state: dict) -> Path:
    output_file = nginx_output_file(root_dir)
    site_config_dir = nginx_site_config_dir(root_dir)
    site_configs = render_domain_config_files(state)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    site_config_dir.mkdir(parents=True, exist_ok=True)
    nginx_site_log_dir(root_dir).mkdir(parents=True, exist_ok=True)

    for stale_file in site_config_dir.glob("*.conf"):
        if stale_file.is_file():
            stale_file.unlink()

    for filename, content in site_configs.items():
        (site_config_dir / filename).write_text(content, encoding="utf-8")

    blocks = generate_nginx_common_blocks(state)
    if site_configs:
        blocks.append(f"include {nginx_path(str(site_config_dir / '*.conf'))};")
    else:
        blocks.append("# No enabled sites.")
    output_file.write_text("\n\n".join(blocks) + "\n", encoding="utf-8")
    return output_file


def run_nginx_command(command: str | None) -> dict:
    if not command:
        return {"configured": False, "ok": False, "stdout": "", "stderr": "No command configured"}

    completed = subprocess.run(
        shlex.split(command),
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    return {
        "configured": True,
        "ok": completed.returncode == 0,
        "returnCode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def nginx_runtime(root_dir: Path) -> dict:
    return {
        "outputFile": str(nginx_output_file(root_dir)),
        "siteConfigDir": str(nginx_site_config_dir(root_dir)),
        "accessLog": str(nginx_access_log_file(root_dir)),
        "siteLogDir": str(nginx_site_log_dir(root_dir)),
        "certDir": str(nginx_cert_dir(root_dir)),
        "testCommand": os.environ.get("NGINX_TEST_CMD", "nginx -t"),
        "reloadCommand": os.environ.get("NGINX_RELOAD_CMD", "nginx -s reload"),
    }


def nginx_cert_dir(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_CERT_DIR", "./nginx/certs"))
    return configured if configured.is_absolute() else root_dir / configured


def parse_nginx_logs(root_dir: Path, limit: int = 500) -> list[dict]:
    log_files = [nginx_access_log_file(root_dir)]
    site_log_dir = nginx_site_log_dir(root_dir)
    if site_log_dir.exists():
        log_files.extend(sorted(site_log_dir.glob("accesslog_*")))

    entries = []
    for log_file in log_files:
        if not log_file.exists() or not log_file.is_file():
            continue
        lines = log_file.read_text(encoding="utf-8", errors="replace").splitlines()
        for index, line in enumerate(reversed(lines[-limit:])):
            try:
                raw = json.loads(line)
            except json.JSONDecodeError:
                continue

            verdict = str(raw.get("verdict") or "allow")
            status = parse_int(raw.get("status"))
            upstream_status = parse_int(raw.get("upstream_status"))
            if verdict == "allow" and status == 461 and upstream_status is None:
                verdict = "challenge"
            if verdict == "allow" and status in {403, 429, 460} and upstream_status is None:
                verdict = "block"
            reason = str(raw.get("reason") or ("Blocked by Nginx WAF" if verdict == "block" else "Allowed"))
            if verdict == "block" and reason == "Allowed":
                reason = "Blocked by ModSecurity or Nginx edge policy"
            if verdict == "challenge" and reason == "Allowed":
                reason = "Browser challenge required"
            entries.append(
                {
                    "id": f"nginx-{safe_identifier(log_file.name)}-{len(lines) - index}",
                    "at": str(raw.get("time") or ""),
                    "siteId": None,
                    "siteName": str(raw.get("host") or "Nginx"),
                    "host": str(raw.get("host") or ""),
                    "method": str(raw.get("method") or ""),
                    "path": str(raw.get("uri") or ""),
                    "ip": str(raw.get("remote_addr") or ""),
                    "verdict": verdict,
                    "statusCode": status,
                    "upstreamStatus": upstream_status,
                    "durationMs": int(float(raw.get("request_time") or 0) * 1000),
                    "reason": reason,
                    "matchedRules": [{"name": reason, "severity": "medium", "action": verdict}] if verdict != "allow" else [],
                    "userAgent": str(raw.get("user_agent") or ""),
                    "referer": str(raw.get("referer") or ""),
                    "requestSize": 0,
                }
            )

    return sorted(entries, key=lambda entry: entry.get("at") or "", reverse=True)[:limit]


def clear_nginx_logs(root_dir: Path) -> None:
    log_files = [nginx_access_log_file(root_dir)]
    site_log_dir = nginx_site_log_dir(root_dir)
    if site_log_dir.exists():
        log_files.extend(sorted(site_log_dir.glob("accesslog_*")))
    for log_file in log_files:
        if log_file.exists() and log_file.is_file():
            log_file.write_text("", encoding="utf-8")


def render_access_maps(state: dict, access_rules: list[dict]) -> list[str]:
    groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
    blocks = []
    for index, rule in enumerate(access_rules, start=1):
        condition_groups = rule.get("conditionGroups") if isinstance(rule.get("conditionGroups"), list) else []
        if condition_groups:
            for group_index, condition_group in enumerate(condition_groups, start=1):
                for condition_index, condition in enumerate(condition_group.get("conditions") or [], start=1):
                    items = collect_condition_ip_items(condition, groups)
                    if items:
                        blocks.append(render_geo_map(access_condition_geo_var(index, group_index, condition_index), items))
            continue

        items = collect_access_ips(rule, groups)
        if not items:
            continue
        blocks.append(render_geo_map(f"sfl_access_ip_{index}", items))
    return blocks


def render_bot_detection_maps() -> list[str]:
    return [
        "map $http_user_agent $sfl_bad_bot_ua {",
        "    default 0;",
        f"    ~*{BOT_BLOCK_UA_PATTERN} 1;",
        "}",
        "",
        "map $http_referer $sfl_bad_referer {",
        "    default 0;",
        f"    ~*{BOT_BLOCK_UA_PATTERN} 1;",
        "}",
        "",
        "map $request_method $sfl_unsafe_method {",
        "    default 0;",
        "    ~*^(?:TRACE|TRACK|CONNECT)$ 1;",
        "}",
        "",
    ]


def render_verified_bot_maps(state: dict, sites: list[dict]) -> list[str]:
    if not any(site_verified_search_bots(site).get("enabled") for site in sites):
        return []

    groups = {group.get("id"): group for group in state.get("ipGroups", []) if group.get("enabled")}
    blocks = []
    provider_vars = []
    for provider_name, provider in VERIFIED_BOT_PROVIDERS.items():
        ip_var = f"sfl_verified_{provider_name}_ip"
        verified_var = f"sfl_verified_{provider_name}_bot"
        ip_ref = f"${ip_var}"
        provider_vars.append(f"${verified_var}")
        blocks.append(render_geo_map(ip_var, ip_group_items(groups.get(provider["id"]))))
        blocks.extend(
            [
                f'map "{ip_ref}:$http_user_agent" ${verified_var} {{',
                "    default 0;",
                f"    ~*^1:.*{provider['userAgentPattern']} 1;",
                "}",
            ]
        )

    blocks.extend(
        [
            f'map "{"|".join(provider_vars)}" $sfl_verified_search_bot {{',
            "    default 0;",
            "    ~1 1;",
            "}",
            "",
        ]
    )
    return blocks


def render_challenge_maps() -> list[str]:
    return [
        "map \"$request_method:$uri\" $sfl_under_attack_bypass {",
        "    default 0;",
        "    ~*^(?:GET|HEAD):/(?:robots\\.txt|sitemap(?:_index)?\\.xml)$ 1;",
        "    ~*^(?:GET|HEAD):/.*\\.(?:css|js|mjs|map|png|jpe?g|gif|webp|avif|svg|ico|woff2?|ttf|eot|mp4|webm|mp3|wav|pdf|txt|xml)$ 1;",
        "}",
        "",
    ]


def render_global_rate_limit_zones(rate_limit: dict, verified_bot_bypass: bool = False) -> list[str]:
    rate = nginx_rate(rate_limit)
    ip_key = "$binary_remote_addr"
    fingerprint_key = '"$remote_addr|$request_method|$http_user_agent"'
    lines = []
    if verified_bot_bypass:
        lines.extend(
            [
                "map $sfl_verified_search_bot $sfl_global_rate_key {",
                "    default $binary_remote_addr;",
                '    1 "";',
                "}",
                "map $sfl_verified_search_bot $sfl_global_rate_fingerprint_key {",
                '    default "$remote_addr|$request_method|$http_user_agent";',
                '    1 "";',
                "}",
                "",
            ]
        )
        ip_key = "$sfl_global_rate_key"
        fingerprint_key = "$sfl_global_rate_fingerprint_key"
    return [
        *lines,
        f"limit_req_zone {ip_key} zone=freewaf_rate:10m rate={rate};",
        f"limit_req_zone {fingerprint_key} zone=freewaf_rate_fingerprint:10m rate={rate};",
    ]


def render_bot_limit_zones(sites: list[dict]) -> list[str]:
    zones = []
    for site in sites:
        protection = site_bot_protection(site)
        if not protection.get("antiReplay"):
            continue
        key = '"$binary_remote_addr|$request_method|$request_uri|$http_user_agent"'
        if site_verified_search_bots(site).get("bypassRateLimit"):
            key_name = bot_replay_key_name(site)
            zones.extend(
                [
                    f'map "$sfl_verified_search_bot:$remote_addr:$request_method:$request_uri:$http_user_agent" ${key_name} {{',
                    '    ~^1: "";',
                    '    default "$remote_addr|$request_method|$request_uri|$http_user_agent";',
                    "}",
                    "",
                ]
            )
            key = f"${key_name}"
        zones.append(f"limit_req_zone {key} zone={bot_replay_zone_name(site)}:10m rate=1r/s;")
    return zones


def render_geo_map(variable_name: str, items: list[str]) -> str:
    lines = [
        f"geo ${variable_name} {{",
        "    default 0;",
    ]
    for item in items:
        lines.append(f"    {item} 1;")
    lines.append("}")
    return "\n".join(lines)


def render_geo_block_maps(sites: list[dict]) -> list[str]:
    blocks = []
    for site in sites:
        config = site_geo_block(site)
        if not config.get("enabled"):
            continue
        variable = geo_block_var_name(site)
        countries = config.get("countries") or []
        cidrs = geo_block_cidrs(countries)
        lines = [
            f"geo ${variable} {{",
            "    default 0;",
        ]
        if cidrs:
            lines.append(f"    # Geo Block: {', '.join(countries)}")
            for cidr in cidrs:
                lines.append(f"    {cidr} 1;")
        else:
            lines.append("    # Geo Block has no CIDR data. Check GEOIP_DB_FILE.")
        lines.append("}")
        blocks.extend(["\n".join(lines), ""])
    return blocks


def geo_block_cidrs(countries: list[str]) -> list[str]:
    country_set = frozenset(str(country or "").strip().upper() for country in countries if str(country or "").strip())
    if not country_set:
        return []
    db_file = geoip_db_file()
    if not db_file.exists() or not db_file.is_file():
        return []
    try:
        mtime = db_file.stat().st_mtime
    except OSError:
        return []
    cache_key = (str(db_file), mtime, tuple(sorted(country_set)))
    cached = GEO_CIDR_CACHE.get(cache_key)
    if cached is not None:
        return cached

    cidrs = []
    try:
        with gzip.open(db_file, "rt", encoding="utf-8", newline="") as source:
            for row in csv.reader(source):
                if len(row) < 3:
                    continue
                code = str(row[2] or "").strip().upper()
                if code not in country_set:
                    continue
                try:
                    start_address = ipaddress.ip_address(row[0].strip())
                    end_address = ipaddress.ip_address(row[1].strip())
                except ValueError:
                    continue
                if start_address.version != end_address.version:
                    continue
                cidrs.extend(str(network) for network in ipaddress.summarize_address_range(start_address, end_address))
    except (OSError, gzip.BadGzipFile, csv.Error):
        cidrs = []

    GEO_CIDR_CACHE.clear()
    GEO_CIDR_CACHE[cache_key] = cidrs
    return cidrs


def geoip_db_file() -> Path:
    return Path(os.environ.get("GEOIP_DB_FILE", "/var/lib/freewaf/geoip/dbip-country-lite.csv.gz"))


def site_hostnames(site: dict) -> list[str]:
    hostnames = site.get("hostnames") if isinstance(site.get("hostnames"), list) else []
    values = [str(hostname).strip() for hostname in hostnames if str(hostname or "").strip()]
    return values or ["_"]


def domain_config_filename(site: dict, hostname: str) -> str:
    site_id = safe_identifier(site.get("id") or site.get("name") or "site")
    domain_id = safe_identifier(str(hostname or "_").replace("*.", "wildcard_").replace("*", "catchall"))
    return f"{site_id}__{domain_id}.conf"


def render_site_server(site: dict, state: dict, certificates: dict[str, dict], hostname: str | None = None) -> str:
    hostnames = [hostname] if hostname else site_hostnames(site)
    defaults = application_defaults(state)
    proxy = site_proxy(site, defaults.get("proxy"))
    modsecurity = site_modsecurity(site, defaults.get("modSecurity"))
    render_site = {**site, "hostnames": hostnames, "proxy": proxy, "modSecurity": modsecurity}
    server_name = " ".join(escape_server_name(name) for name in hostnames)
    app_type = application_type(site)
    upstreams = site_upstreams(site)
    upstream_scheme = urlparse(upstreams[0]).scheme if upstreams else "http"
    upstream_name = backend_name(site, hostname)
    tls = site.get("tls") or {}
    certificate = certificates.get(tls.get("certificateId"))
    has_tls = bool(tls.get("enabled") and certificate)
    ports = site_ports(site)
    http_ports = [port for port, is_ssl in ports if not is_ssl]
    https_ports = [port for port, is_ssl in ports if is_ssl]
    blocks = [render_upstream(upstream_name, upstreams)] if app_type == "reverse_proxy" and upstreams else []

    redirect_code = int(proxy.get("redirectStatusCode") or site.get("redirectStatusCode") or 301)
    first_https_port = https_ports[0] if https_ports else int(site.get("listen") or 443)
    if has_tls and proxy.get("forceHttps") and redirect_code:
        for port in http_ports or [int(tls.get("httpListen") or 80)]:
            blocks.append(render_redirect_server(render_site, state, server_name, port, first_https_port, proxy, redirect_code))
    else:
        for port in http_ports:
            blocks.append(render_proxy_server(render_site, state, certificates, upstream_name, upstream_scheme, port, False, server_name, proxy))

    if https_ports:
        if has_tls:
            for port in https_ports:
                blocks.append(render_proxy_server(render_site, state, certificates, upstream_name, upstream_scheme, port, True, server_name, proxy))
        else:
            blocks.append(
                "\n".join(
                    [
                        f"# Site {nginx_comment(site.get('name'))} has HTTPS ports configured,",
                        "# but TLS is disabled or no valid certificate is selected.",
                    ]
                )
            )

    if not blocks:
        blocks.append(render_proxy_server(render_site, state, certificates, upstream_name, upstream_scheme, int(site.get("listen") or 8080), False, server_name, proxy))

    return "\n\n".join(blocks)


def render_upstream(name: str, upstreams: list[str]) -> str:
    lines = [f"upstream {name} {{"]
    for upstream in upstreams:
        parsed = urlparse(upstream)
        lines.append(f"    server {nginx_path(parsed.netloc)};")
    lines.extend(["    keepalive 128;", "    keepalive_timeout 75;", "}"])
    return "\n".join(lines)


def render_redirect_server(site: dict, state: dict, server_name: str, port: int, https_port: int, proxy: dict, redirect_code: int) -> str:
    listen_suffix = " default_server" if proxy.get("defaultServer") else ""
    lines = [
        "server {",
        f"    listen 0.0.0.0:{port}{listen_suffix};",
        *render_ipv6_listen(port, False, proxy),
        f"    server_name {server_name};",
        "",
        "    set $sfl_block 0;",
        "    set $sfl_allow 0;",
        "    set $sfl_challenge 0;",
        "    set $sfl_verdict allow;",
        "    set $sfl_reason \"Allowed\";",
        "",
        *render_challenge_validation(site),
        "",
        *render_log_directives(site, proxy),
        "    error_page 460 = @freewaf_block;",
        "    error_page 461 = @freewaf_challenge;",
        *render_rate_limit_error_page(site),
        "",
        *render_modsecurity_directives(site),
        *render_site_waf_directives(site, state),
        "",
        *render_safeline_locations(site),
        "",
        *render_internal_waf_locations(site, state),
        "",
        "    location / {",
        "        if ($sfl_block = 1) {",
        "            return 460;",
        "        }",
        "        if ($sfl_challenge = 1) {",
        "            return 461;",
        "        }",
        *render_http_flood_modsecurity_rules(site, state),
        *render_rate_limit(state, site),
        *render_bot_replay_limit(site),
        f"        return {redirect_code} https://$host:{https_port}$request_uri;",
        "    }",
        "}",
    ]
    return "\n".join(lines)


def render_proxy_server(
    site: dict,
    state: dict,
    certificates: dict[str, dict],
    upstream_name: str,
    upstream_scheme: str,
    port: int,
    is_ssl: bool,
    server_name: str,
    proxy: dict,
) -> str:
    tls = site.get("tls") or {}
    certificate = certificates.get(tls.get("certificateId"))
    listen_flags = []
    if is_ssl:
        listen_flags.append("ssl")
        if proxy.get("http2"):
            listen_flags.append("http2")
    if proxy.get("defaultServer"):
        listen_flags.append("default_server")
    listen_suffix = f" {' '.join(listen_flags)}" if listen_flags else ""

    lines = [
        "server {",
        f"    listen 0.0.0.0:{port}{listen_suffix};",
        *render_ipv6_listen(port, is_ssl, proxy),
        f"    server_name {server_name};",
        "",
        "    set $sfl_block 0;",
        "    set $sfl_allow 0;",
        "    set $sfl_challenge 0;",
        "    set $sfl_verdict allow;",
        "    set $sfl_reason \"Allowed\";",
        "",
        *render_challenge_validation(site),
        "",
        *render_log_directives(site, proxy),
        "    error_page 460 = @freewaf_block;",
        "    error_page 461 = @freewaf_challenge;",
        *render_rate_limit_error_page(site),
        "    error_page 502 =502 /.safeline/bad_gateway_page;",
        "    error_page 504 =504 /.safeline/gateway_timeout_page;",
        "",
    ]
    if is_ssl and certificate:
        lines.extend(
            [
                f"    ssl_certificate {nginx_path(certificate['certFile'])};",
                f"    ssl_certificate_key {nginx_path(certificate['keyFile'])};",
                "    ssl_protocols TLSv1.2 TLSv1.3;",
                "    ssl_session_cache shared:SSL:10m;",
                "    error_page 497 =302 https://$host:$server_port$request_uri;",
                "",
            ]
        )

    if proxy.get("strictHost"):
        lines.extend(render_strict_host(site))

    lines.extend(render_modsecurity_directives(site))
    lines.extend(render_compression_directives(proxy))

    lines.extend(render_site_waf_directives(site, state))
    lines.extend(
        [
            "",
            *render_safeline_locations(site),
            "",
            *render_internal_waf_locations(site, state),
            "",
            *render_wordpress_cache_min_fallback_location(site),
            "    location / {",
            "        if ($sfl_block = 1) {",
            "            return 460;",
            "        }",
            "        if ($sfl_challenge = 1) {",
            "            return 461;",
            "        }",
            *render_application_location(site, state, upstream_name, upstream_scheme, proxy, is_ssl),
            "    }",
            "}",
        ]
    )

    return "\n".join(lines)


def render_wordpress_cache_min_fallback_location(site: dict) -> list[str]:
    if application_type(site) != "reverse_proxy":
        return []
    return [
        "    location ~ ^/wp-content/cache/min/1/(.+)$ {",
        "        rewrite ^/wp-content/cache/min/1/(.+)$ /$1 last;",
        "    }",
        "",
    ]


def render_site_waf_directives(site: dict, state: dict) -> list[str]:
    rules = [
        rule
        for rule in state.get("rules", [])
        if rule.get("enabled")
        and rule.get("action") != "allow"
        and (rule.get("siteId") == "*" or rule.get("siteId") == site.get("id"))
        and should_emit_rule_for_site(rule, site)
    ]
    allow_rules = [
        rule
        for rule in state.get("rules", [])
        if rule.get("enabled")
        and rule.get("action") == "allow"
        and (rule.get("siteId") == "*" or rule.get("siteId") == site.get("id"))
    ]
    access_rules = [
        (index, rule)
        for index, rule in enumerate([rule for rule in state.get("accessRules", []) if rule.get("enabled")], start=1)
        if rule.get("siteId") in {"*", site.get("id")}
    ]

    lines = []
    rule_index = 0
    for access_index, access_rule in [item for item in access_rules if item[1].get("action") == "allow"]:
        rule_index += 1
        lines.extend(render_access_rule_if(access_rule, access_index, "allow", rule_index, state))

    for access_index, access_rule in [item for item in access_rules if item[1].get("action") != "allow"]:
        rule_index += 1
        effect = "monitor" if site.get("mode") == "monitor" or access_rule.get("action") == "monitor" else "block"
        lines.extend(render_access_rule_if(access_rule, access_index, effect, rule_index, state))

    for rule in allow_rules:
        rule_index += 1
        lines.extend(render_rule_if(rule, "allow", rule_index))

    for rule in rules:
        rule_index += 1
        if site.get("mode") == "monitor" or rule.get("action") == "monitor":
            lines.extend(render_rule_if(rule, "monitor", rule_index))
        else:
            lines.extend(render_rule_if(rule, "block", rule_index))

    lines.extend(render_geo_block(site))
    lines.extend(render_bot_protection(site))
    lines.extend(render_under_attack_protection(site))
    lines.extend(render_acl_notes(site))
    return lines


def render_internal_waf_locations(site: dict, state: dict) -> list[str]:
    lines = [
        "    location @freewaf_block {",
        "        internal;",
        "        add_header X-FreeWAF-Verdict block always;",
        "        default_type text/html;",
        f"        return 403 '{block_page(site)}';",
        "    }",
        "",
        "    location @freewaf_rate_limited {",
        "        internal;",
        "        set $sfl_verdict block;",
        "        set $sfl_reason \"HTTP flood rate limit\";",
        "        add_header X-FreeWAF-Verdict block always;",
        "        default_type text/html;",
        f"        return 429 '{rate_limit_page(site)}';",
        "    }",
    ]
    if not site_uses_challenge(site):
        return lines

    upstream = challenge_backend_url(state)
    secret = nginx_string(challenge_secret())
    common_proxy_headers = [
        f"        proxy_set_header X-FreeWAF-Challenge-Secret \"{secret}\";",
        f"        proxy_set_header X-FreeWAF-Challenge-Site \"{nginx_string(site.get('id') or '')}\";",
        "        proxy_set_header X-FreeWAF-Challenge-Host $host;",
        "        proxy_set_header X-Real-IP $remote_addr;",
        "        proxy_set_header X-Forwarded-Proto $scheme;",
        "        proxy_set_header User-Agent $http_user_agent;",
        "        proxy_pass_request_body on;",
    ]
    tls_proxy = ["        proxy_ssl_verify off;"] if upstream.startswith("https://") else []
    lines.extend(
        [
            "",
            "    location @freewaf_challenge {",
            "        internal;",
            "        set $sfl_verdict challenge;",
            "        set $sfl_reason \"Browser challenge required\";",
            "        add_header X-FreeWAF-Verdict challenge always;",
            "        add_header Cache-Control \"no-store\" always;",
            *render_challenge_location_modsecurity_bypass(),
            "        proxy_set_header X-FreeWAF-Challenge-Render 1;",
            *common_proxy_headers,
            *tls_proxy,
            f"        proxy_pass {upstream};",
            "    }",
            "",
            "    location = /.freewaf/challenge/verify {",
            *render_challenge_location_modsecurity_bypass(),
            "        proxy_set_header X-FreeWAF-Challenge-Render 0;",
            *common_proxy_headers,
            *tls_proxy,
            f"        proxy_pass {upstream};",
            "    }",
        ]
    )
    return lines


def render_challenge_location_modsecurity_bypass() -> list[str]:
    if os.environ.get("NGINX_HAS_MODSECURITY", "false").lower() == "true":
        return ["        modsecurity off;"]
    return []


def challenge_backend_url(state: dict) -> str:
    panel = state.get("settings", {}).get("panel", {})
    scheme = "https" if panel.get("httpsEnabled") else "http"
    port = max(1, min(parse_int(os.environ.get("ADMIN_PORT")) or 7001, 65535))
    return f"{scheme}://127.0.0.1:{port}"


def render_challenge_validation(site: dict) -> list[str]:
    if not site_uses_challenge(site):
        return []
    secret = nginx_string(challenge_secret())
    return [
        "    secure_link \"$cookie_freewaf_challenge,$cookie_freewaf_challenge_expires\";",
        f"    secure_link_md5 \"$secure_link_expires|$host|$remote_addr|$http_user_agent|{secret}\";",
        "    set $sfl_challenge_passed 0;",
        "    if ($secure_link = \"1\") {",
        "        set $sfl_challenge_passed 1;",
        "    }",
    ]


def application_type(site: dict) -> str:
    value = str(site.get("applicationType") or "reverse_proxy").lower().replace("-", "_")
    return value if value in {"reverse_proxy", "static_files", "redirect"} else "reverse_proxy"


def render_application_location(site: dict, state: dict, upstream_name: str, upstream_scheme: str, proxy: dict, is_ssl: bool) -> list[str]:
    app_type = application_type(site)
    if app_type == "redirect":
        redirect = site.get("redirect") if isinstance(site.get("redirect"), dict) else {}
        address = nginx_path(redirect.get("address") or "http://127.0.0.1")
        status = int(redirect.get("statusCode") or proxy.get("redirectStatusCode") or 301)
        return [
            *render_http_flood_modsecurity_rules(site, state),
            *render_bot_rate_modsecurity_rules(site, state),
            *render_hsts_header(proxy, is_ssl),
            *render_dynamic_protection_headers(site),
            *render_bot_replay_limit(site),
            f"        return {status} {address}$request_uri;",
        ]

    if app_type == "static_files":
        root = static_root(site)
        return [
            *render_http_flood_modsecurity_rules(site, state),
            *render_bot_rate_modsecurity_rules(site, state),
            *render_hsts_header(proxy, is_ssl),
            *render_dynamic_protection_headers(site),
            *render_bot_replay_limit(site),
            f"        root {nginx_path(root)};",
            "        try_files $uri $uri/ =404;",
        ]

    lines = [
        *render_http_flood_modsecurity_rules(site, state),
        *render_bot_rate_modsecurity_rules(site, state),
        "        proxy_http_version 1.1;",
        "        proxy_set_header Upgrade $http_upgrade;",
        "        proxy_set_header Connection $sfl_connection_upgrade;",
        "        proxy_set_header X-Real-IP $remote_addr;",
    ]
    if proxy.get("modifyHostHeader"):
        lines.append(f"        proxy_set_header Host {proxy.get('hostHeader') or '$http_host'};")
    if proxy.get("forwardedHeaders"):
        lines.extend(
            [
                f"        proxy_set_header X-Forwarded-For {xff_value(proxy)};",
                f"        proxy_set_header X-Forwarded-Proto {proxy.get('xForwardedProto') or '$scheme'};",
                f"        proxy_set_header X-Forwarded-Host {proxy.get('xForwardedHost') or '$http_host'};",
            ]
        )
    lines.extend(
        [
            "        proxy_set_header X-FreeWAF $sfl_verdict;",
            *render_hsts_header(proxy, is_ssl),
            *render_dynamic_protection_headers(site),
            *render_proxy_ssl(upstream_scheme, proxy),
            *render_rate_limit(state, site),
            *render_bot_replay_limit(site),
            f"        proxy_pass {upstream_scheme}://{upstream_name};",
        ]
    )
    return lines


def static_root(site: dict) -> str:
    static = site.get("static") if isinstance(site.get("static"), dict) else {}
    if static.get("root"):
        return str(static["root"])
    base = os.environ.get("NGINX_STATIC_ROOT", "./public/static").replace("\\", "/").rstrip("/")
    return f"{base}/{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def site_upstreams(site: dict) -> list[str]:
    if application_type(site) != "reverse_proxy":
        return []
    upstreams = site.get("upstreams") if isinstance(site.get("upstreams"), list) else []
    values = [str(item) for item in upstreams if str(item or "").strip()]
    return values or [str(site.get("origin") or "http://127.0.0.1:9090")]


def backend_name(site: dict, hostname: str | None = None) -> str:
    suffix = f"_{safe_identifier(hostname)}" if hostname else ""
    return f"backend_{safe_identifier(site.get('id') or site.get('name') or 'site')}{suffix}"


def site_ports(site: dict) -> list[tuple[int, bool]]:
    raw_ports = site.get("ports") if isinstance(site.get("ports"), list) else []
    parsed = [parse_site_port(value) for value in raw_ports]
    parsed = [value for value in parsed if value]
    if parsed:
        return list(dict.fromkeys(parsed))
    tls = site.get("tls") or {}
    if tls.get("enabled"):
        if tls.get("redirectHttp"):
            return [(int(tls.get("httpListen") or 80), False), (int(site.get("listen") or 443), True)]
        return [(int(site.get("listen") or 443), True)]
    return [(int(site.get("listen") or 8080), False)]


def parse_site_port(value) -> tuple[int, bool] | None:
    item = str(value or "").strip().lower()
    if not item:
        return None
    is_ssl = item.endswith("_ssl")
    raw_port = item[:-4] if is_ssl else item
    if not re.match(r"^\d+$", raw_port):
        return None
    port = int(raw_port)
    if port < 1 or port > 65535:
        return None
    return port, is_ssl


def application_defaults(state: dict) -> dict:
    settings = state.get("settings") if isinstance(state.get("settings"), dict) else {}
    defaults = settings.get("applicationDefaults") if isinstance(settings.get("applicationDefaults"), dict) else {}
    return {
        "proxy": defaults.get("proxy") if isinstance(defaults.get("proxy"), dict) else {},
        "modSecurity": defaults.get("modSecurity") if isinstance(defaults.get("modSecurity"), dict) else {},
    }


def site_proxy(site: dict, defaults: dict | None = None) -> dict:
    tls = site.get("tls") if isinstance(site.get("tls"), dict) else {}
    site_proxy_config = site.get("proxy") if isinstance(site.get("proxy"), dict) else {}
    defaults = defaults if isinstance(defaults, dict) else {}
    proxy = {**site_proxy_config, **defaults}
    return {
        "forceHttps": bool(proxy.get("forceHttps", tls.get("redirectHttp", False))),
        "redirectStatusCode": int(proxy.get("redirectStatusCode") or site.get("redirectStatusCode") or 301),
        "hsts": bool(proxy.get("hsts", bool(tls.get("enabled")))),
        "hstsMaxAge": str(proxy.get("hstsMaxAge") or "15768000"),
        "gzip": proxy.get("gzip") is not False,
        "brotli": bool(proxy.get("brotli")),
        "http2": proxy.get("http2", tls.get("http2", True)) is not False,
        "ipv6": bool(proxy.get("ipv6")),
        "resetXff": proxy.get("resetXff") is not False,
        "defaultServer": bool(proxy.get("defaultServer")),
        "strictHost": bool(proxy.get("strictHost")),
        "accessLog": proxy.get("accessLog") is not False,
        "modifyHostHeader": proxy.get("modifyHostHeader") is not False,
        "forwardedHeaders": proxy.get("forwardedHeaders") is not False,
        "hostHeader": nginx_value(proxy.get("hostHeader") or "$http_host"),
        "xForwardedProto": nginx_value(proxy.get("xForwardedProto") or "$scheme"),
        "xForwardedHost": nginx_value(proxy.get("xForwardedHost") or "$http_host"),
        "proxySslServerName": proxy.get("proxySslServerName") is not False,
    }


def site_modsecurity(site: dict, defaults: dict | None = None) -> dict:
    config = site.get("modSecurity") if isinstance(site.get("modSecurity"), dict) else {}
    defaults = defaults if isinstance(defaults, dict) else {}
    merged = {**config, **defaults}
    mode = str(merged.get("mode") or "on").lower()
    ruleset = str(merged.get("ruleset") or "comodo").lower()
    return {
        "enabled": merged.get("enabled") is not False,
        "mode": mode if mode in {"on", "detection_only"} else "on",
        "ruleset": ruleset if ruleset in {"comodo", "owasp"} else "comodo",
        "requestBodyLimit": min(max(int(merged.get("requestBodyLimit") or 13107200), 131072), 1073741824),
    }


def render_modsecurity_directives(site: dict) -> list[str]:
    config = site.get("modSecurity") if isinstance(site.get("modSecurity"), dict) else {}
    bot_rate_required = bot_rate_challenge_required(site)
    http_flood_required = http_flood_cooldown_required(site)
    if not config.get("enabled") and not bot_rate_required and not http_flood_required:
        return []
    if os.environ.get("NGINX_HAS_MODSECURITY", "false").lower() != "true":
        lines = []
        if config.get("enabled"):
            lines.append("    # ModSecurity is enabled for this application, but NGINX_HAS_MODSECURITY is not true.")
        if bot_rate_required:
            lines.append("    # Bot Protect rate thresholds require ModSecurity, but NGINX_HAS_MODSECURITY is not true.")
        if http_flood_required:
            lines.append("    # HTTP Flood temporary block thresholds require ModSecurity, but NGINX_HAS_MODSECURITY is not true.")
        lines.append("")
        return lines

    ruleset = str(config.get("ruleset") or "comodo").lower()
    if not config.get("enabled"):
        rules_file = os.environ.get("NGINX_MODSECURITY_BASE_RULES_FILE", "/etc/freewaf/modsecurity/base.conf")
    elif ruleset == "owasp":
        rules_file = os.environ.get("NGINX_MODSECURITY_OWASP_RULES_FILE", "/etc/freewaf/modsecurity/owasp-crs.conf")
    else:
        rules_file = os.environ.get("NGINX_MODSECURITY_COMODO_RULES_FILE", "/etc/freewaf/modsecurity/comodo.conf")
    rules_file = rules_file.strip()
    if not rules_file:
        return [
            f"    # ModSecurity {nginx_comment(ruleset)} rules file is not configured.",
            "",
        ]

    engine = "DetectionOnly" if config.get("mode") == "detection_only" or site.get("mode") == "monitor" else "On"
    body_limit = min(max(int(config.get("requestBodyLimit") or 13107200), 131072), 1073741824)
    lines = [
        "    modsecurity on;",
        f"    modsecurity_rules_file {nginx_path(rules_file)};",
        f"    modsecurity_rules 'SecRuleEngine {engine}';",
        f"    modsecurity_rules 'SecRequestBodyLimit {body_limit}';",
        "",
    ]
    return lines


def bot_rate_challenge_required(site: dict) -> bool:
    protection = site_bot_protection(site)
    rate = protection.get("rateChallenge") or {}
    return bool(protection.get("antiBotChallenge") and rate.get("enabled"))


def http_flood_cooldown_required(site: dict) -> bool:
    limit = active_acl_access_limit(site)
    if not limit or not site_features(site).get("httpFlood"):
        return False
    if acl_limit_action(limit) not in {"block", "challenge_v1"}:
        return False
    count = max(1, int(limit.get("count") or 200))
    block_count = int(limit.get("blockCount") or 0)
    return block_count > count


def render_bot_rate_modsecurity_rules(site: dict, state: dict | None = None, indent: str = "        ") -> list[str]:
    protection = site_bot_protection(site)
    rate = protection.get("rateChallenge") or {}
    if (
        not protection.get("antiBotChallenge")
        or not rate.get("enabled")
        or os.environ.get("NGINX_HAS_MODSECURITY", "false").lower() != "true"
    ):
        return []

    window_seconds = bot_rate_window_seconds(rate)
    challenge_count = max(1, int(rate.get("challengeCount") or DEFAULT_BOT_RATE_CHALLENGE["challengeCount"]))
    block_count = max(challenge_count + 1, int(rate.get("blockCount") or DEFAULT_BOT_RATE_CHALLENGE["blockCount"]))
    block_seconds = bot_rate_block_minutes(rate) * 60
    site_key = safe_identifier(site.get("id") or site.get("name") or "site").lower()
    window_var = f"freewaf_{site_key}_bot_window"
    count_var = f"freewaf_{site_key}_bot_count"
    blocked_var = f"freewaf_{site_key}_bot_blocked"
    ua_hash_var = f"freewaf_{site_key}_bot_ua_hash"
    accept_hash_var = f"freewaf_{site_key}_bot_accept_hash"
    language_hash_var = f"freewaf_{site_key}_bot_language_hash"
    client_hints_hash_var = f"freewaf_{site_key}_bot_client_hints_hash"
    fingerprint_key = (
        f"freewaf_{site_key}_bot_%{{REMOTE_ADDR}}_%{{tx.{ua_hash_var}}}_"
        f"%{{tx.{accept_hash_var}}}_%{{tx.{language_hash_var}}}_%{{tx.{client_hints_hash_var}}}"
    )
    marker = f"FREEWAF_BOT_RATE_DONE_{safe_identifier(site.get('id') or site.get('name') or 'site').upper()}"
    base = modsecurity_rule_id_base(site)
    rules = [
        *render_verified_bot_modsecurity_skip_rules(state or {}, site, marker, base + 120, require_rate_bypass=True),
        (
            f'SecAction "id:{base + 1},phase:1,nolog,pass,'
            f'setvar:tx.{ua_hash_var}=none,setvar:tx.{accept_hash_var}=none,'
            f'setvar:tx.{language_hash_var}=none,setvar:tx.{client_hints_hash_var}=none,'
            f'setvar:tx.{window_var}=%{{TIME_YEAR}}-%{{TIME_MON}}-%{{TIME_DAY}}-%{{TIME_HOUR}}-%{{TIME_MIN}}"'
        ),
        render_modsecurity_header_hash_rule("REQUEST_HEADERS:User-Agent", ua_hash_var, base + 20),
        render_modsecurity_header_hash_rule("REQUEST_HEADERS:Accept", accept_hash_var, base + 21),
        render_modsecurity_header_hash_rule("REQUEST_HEADERS:Accept-Language", language_hash_var, base + 22),
        render_modsecurity_header_hash_rule("REQUEST_HEADERS:Sec-CH-UA", client_hints_hash_var, base + 23),
        f'SecAction "id:{base + 29},phase:1,nolog,pass,initcol:global={fingerprint_key}"',
        *render_modsecurity_second_bucket_rules(window_seconds, window_var, base + 30),
        (
            f'SecRule GLOBAL:{blocked_var} "@eq 1" '
            f'"id:{base + 79},phase:1,deny,status:460,log,msg:FreeWAFBotRateCooldown"'
        ),
        (
            f'SecRule GLOBAL:{window_var} "!@streq %{{tx.{window_var}}}" "id:{base + 80},phase:1,nolog,pass,'
            f'setvar:global.{count_var}=0,setvar:global.{window_var}=%{{tx.{window_var}}}"'
        ),
        f'SecAction "id:{base + 81},phase:1,nolog,pass,setvar:global.{count_var}=+1"',
        (
            f'SecRule GLOBAL:{count_var} "@gt {block_count}" '
            f'"id:{base + 82},phase:1,deny,status:460,log,msg:FreeWAFBotRateBlock,'
            f'setvar:global.{blocked_var}=1,expirevar:global.{blocked_var}={block_seconds}"'
        ),
        (
            f'SecRule REQUEST_COOKIES:freewaf_challenge "@rx .+" '
            f'"id:{base + 83},phase:1,nolog,pass,skipAfter:{marker}"'
        ),
        (
            f'SecRule GLOBAL:{count_var} "@gt {challenge_count}" '
            f'"id:{base + 84},phase:1,deny,status:461,nolog,msg:FreeWAFBotRateChallenge"'
        ),
        f"SecMarker {marker}",
    ]
    return [f"{indent}modsecurity_rules '{rule}';" for rule in rules]


def render_modsecurity_header_hash_rule(target: str, tx_var: str, rule_id: int) -> str:
    return (
        f'SecRule {target} "@rx .+" '
        f'"id:{rule_id},phase:1,nolog,pass,t:none,t:sha1,t:hexEncode,setvar:tx.{tx_var}=%{{MATCHED_VAR}}"'
    )


def render_modsecurity_second_bucket_rules(window_seconds: int, window_var: str, first_rule_id: int) -> list[str]:
    if window_seconds >= 60:
        return []
    rules = []
    for bucket, start in enumerate(range(0, 60, window_seconds)):
        end = min(start + window_seconds - 1, 59)
        regex = modsecurity_second_range_regex(start, end)
        rules.append(
            f'SecRule TIME_SEC "{regex}" "id:{first_rule_id + bucket},phase:1,nolog,pass,'
            f'setvar:tx.{window_var}=%{{tx.{window_var}}}-{bucket}"'
        )
    return rules


def modsecurity_second_range_regex(start: int, end: int) -> str:
    values = []
    for second in range(start, end + 1):
        if second < 10:
            values.append(f"0?{second}")
        else:
            values.append(str(second))
    return "^(?:" + "|".join(values) + ")$"


def bot_rate_window_seconds(rate: dict) -> int:
    value = int(rate.get("windowSeconds") or DEFAULT_BOT_RATE_CHALLENGE["windowSeconds"])
    return value if value in {5, 10, 15, 20, 30, 60} else DEFAULT_BOT_RATE_CHALLENGE["windowSeconds"]


def bot_rate_block_minutes(rate: dict) -> int:
    value = int(rate.get("blockMinutes") or rate.get("blockMin") or DEFAULT_BOT_RATE_CHALLENGE["blockMinutes"])
    return value if value in {10, 30, 60} else DEFAULT_BOT_RATE_CHALLENGE["blockMinutes"]


def render_http_flood_modsecurity_rules(site: dict, state: dict | None = None, indent: str = "        ") -> list[str]:
    if not http_flood_cooldown_required(site) or os.environ.get("NGINX_HAS_MODSECURITY", "false").lower() != "true":
        return []

    limit = active_acl_access_limit(site) or {}
    window_seconds = max(1, int(limit.get("period") or 10))
    count = max(1, int(limit.get("count") or 200))
    block_count = max(count + 1, int(limit.get("blockCount") or 500))
    block_seconds = max(1, int(limit.get("blockMin") or 60)) * 60
    site_key = safe_identifier(site.get("id") or site.get("name") or "site").lower()
    window_var = f"freewaf_{site_key}_flood_window"
    count_var = f"freewaf_{site_key}_flood_count"
    blocked_var = f"freewaf_{site_key}_flood_blocked"
    base = modsecurity_rule_id_base(site) + 200
    marker = f"FREEWAF_HTTP_FLOOD_DONE_{safe_identifier(site.get('id') or site.get('name') or 'site').upper()}"
    rules = [
        *render_verified_bot_modsecurity_skip_rules(state or {}, site, marker, base + 80, require_rate_bypass=True),
        (
            f'SecAction "id:{base + 1},phase:1,nolog,pass,initcol:ip=%{{REMOTE_ADDR}},'
            f'setvar:tx.{window_var}=%{{TIME_YEAR}}-%{{TIME_MON}}-%{{TIME_DAY}}-%{{TIME_HOUR}}-%{{TIME_MIN}}"'
        ),
        *render_modsecurity_second_bucket_rules(window_seconds, window_var, base + 10),
        (
            f'SecRule IP:{blocked_var} "@eq 1" '
            f'"id:{base + 69},phase:1,deny,status:460,log,msg:FreeWAFHttpFloodCooldown"'
        ),
        (
            f'SecRule IP:{window_var} "!@streq %{{tx.{window_var}}}" "id:{base + 70},phase:1,nolog,pass,'
            f'setvar:ip.{count_var}=0,setvar:ip.{window_var}=%{{tx.{window_var}}}"'
        ),
        f'SecAction "id:{base + 71},phase:1,nolog,pass,setvar:ip.{count_var}=+1"',
        (
            f'SecRule IP:{count_var} "@gt {block_count}" '
            f'"id:{base + 72},phase:1,deny,status:460,log,msg:FreeWAFHttpFloodBlock,'
            f'setvar:ip.{blocked_var}=1,expirevar:ip.{blocked_var}={block_seconds}"'
        ),
        f"SecMarker {marker}",
    ]
    return [f"{indent}modsecurity_rules '{rule}';" for rule in rules]


def render_verified_bot_modsecurity_skip_rules(
    state: dict,
    site: dict,
    marker: str,
    first_rule_id: int,
    require_rate_bypass: bool = False,
) -> list[str]:
    config = site_verified_search_bots(site)
    if not config.get("enabled"):
        return []
    if require_rate_bypass and not config.get("bypassRateLimit"):
        return []

    groups = {group.get("id"): group for group in state.get("ipGroups", []) if group.get("enabled")}
    rules = []
    rule_id = first_rule_id
    for provider in VERIFIED_BOT_PROVIDERS.values():
        items = ip_group_items(groups.get(provider["id"]))
        if not items:
            continue
        for chunk in chunks(items, 80):
            rules.append(
                "\n".join(
                    [
                        f'SecRule REMOTE_ADDR "@ipMatch {",".join(chunk)}" '
                        f'"id:{rule_id},phase:1,nolog,pass,chain,skipAfter:{marker}"',
                        f'    SecRule REQUEST_HEADERS:User-Agent "@rx (?i:{provider["userAgentPattern"]})" "t:none"',
                    ]
                )
            )
            rule_id += 1
    return rules


def modsecurity_rule_id_base(site: dict) -> int:
    value = safe_identifier(site.get("id") or site.get("name") or "site")
    digest = sum((index + 1) * ord(char) for index, char in enumerate(value)) % 100000
    return 8_600_000 + (digest * 1000)


def render_ipv6_listen(port: int, is_ssl: bool, proxy: dict) -> list[str]:
    if not proxy.get("ipv6"):
        return []
    flags = ["ssl"] if is_ssl else []
    if is_ssl and proxy.get("http2"):
        flags.append("http2")
    if proxy.get("defaultServer"):
        flags.append("default_server")
    suffix = f" {' '.join(flags)}" if flags else ""
    return [f"    listen [::]:{port}{suffix};"]


def render_log_directives(site: dict, proxy: dict) -> list[str]:
    lines = []
    if proxy.get("accessLog"):
        lines.append(f"    access_log {nginx_site_access_log_directive(site)} freewaf;")
    else:
        lines.append("    access_log off;")
    lines.append(f"    error_log {nginx_site_error_log_directive(site)};")
    return lines


def render_strict_host(site: dict) -> list[str]:
    regex = server_names_regex(site.get("hostnames") or [])
    if not regex:
        return []
    return [
        f"    if ($host !~* {nginx_regex(regex)}) {{",
        "        return 404;",
        "    }",
        "",
    ]


def server_names_regex(hostnames: list[str]) -> str:
    patterns = []
    for hostname in hostnames:
        item = str(hostname or "").strip().lower()
        if not item or item in {"*", "_"}:
            continue
        if item.startswith("*."):
            patterns.append(r"(?:.+\.)?" + re.escape(item[2:]))
        else:
            patterns.append(re.escape(item))
    return f"^(?:{'|'.join(patterns)})$" if patterns else ""


def render_compression_directives(proxy: dict) -> list[str]:
    lines = [f"    gzip {'on' if proxy.get('gzip') else 'off'};"]
    if proxy.get("brotli"):
        if os.environ.get("NGINX_HAS_BROTLI", "false").lower() == "true":
            lines.append("    brotli on;")
        else:
            lines.append("    # Brotli is enabled in this application; set NGINX_HAS_BROTLI=true to emit brotli on;")
    lines.append("")
    return lines


def render_acl_notes(site: dict) -> list[str]:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    if not acl.get("enabled"):
        return []
    notes = []
    attack = acl.get("attackLimit") if isinstance(acl.get("attackLimit"), dict) else {}
    error = acl.get("errorLimit") if isinstance(acl.get("errorLimit"), dict) else {}
    if attack.get("enabled"):
        notes.extend(
            [
                f"    # Basic Attack Limit: {int(attack.get('count') or 10)} attacks / {int(attack.get('period') or 60)}s -> {attack.get('action') or 'block'}.",
                "    # Native Nginx cannot count detector-classified attacks without a detector module.",
            ]
        )
    if error.get("enabled"):
        notes.extend(
            [
                f"    # Basic Error Limit: {int(error.get('count') or 10)} responses / {int(error.get('period') or 10)}s for status {', '.join(error.get('statusCodes') or ['403', '404'])}.",
                "    # SafeLine CE enforces this via management/detector state; FreeWAF records the policy for parity.",
            ]
        )
    return [*notes, ""] if notes else []


def render_safeline_locations(site: dict) -> list[str]:
    challenge_url = os.environ.get("NGINX_CHAOS_CHALLENGE_URL", "").strip()
    static_dir = os.environ.get("NGINX_FREEWAF_STATIC_DIR", "").strip()
    lines = [
        "    location = /.safeline/forbidden_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 403 '{block_page(site)}';",
        "    }",
        "    location = /.safeline/acl_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 429 '{error_page_html('Request limited', 'FreeWAF rate limit was triggered.')}';",
        "    }",
        "    location = /.safeline/bad_gateway_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 502 '{error_page_html('Bad gateway', 'The protected upstream did not return a valid response.')}';",
        "    }",
        "    location = /.safeline/gateway_timeout_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 504 '{error_page_html('Gateway timeout', 'The protected upstream timed out.')}';",
        "    }",
        "    location ^~ /.safeline/offline_page {",
        "        internal;",
        "        add_header cache-control no-cache;",
        "        default_type text/html;",
        f"        return 503 '{error_page_html('Application offline', 'This application is temporarily unavailable.')}';",
        "    }",
        "    location ^~ /.safeline/challenge/v2/ {",
    ]
    if challenge_url:
        lines.extend(
            [
                f"        proxy_pass {nginx_path(challenge_url)};",
                "        proxy_set_header Host $host;",
            ]
        )
    else:
        lines.append("        return 204;")
    lines.extend(["    }", "    location ^~ /.safeline/static {"])
    if static_dir:
        lines.extend(["        charset utf-8;", f"        alias {nginx_path(static_dir)};"])
    else:
        lines.append("        return 404;")
    lines.append("    }")
    return lines


def xff_value(proxy: dict) -> str:
    return "$remote_addr" if proxy.get("resetXff") else "$proxy_add_x_forwarded_for"


def render_hsts_header(proxy: dict, is_ssl: bool) -> list[str]:
    if not is_ssl or not proxy.get("hsts"):
        return []
    max_age = re.sub(r"[^0-9]", "", str(proxy.get("hstsMaxAge") or "15768000")) or "15768000"
    return [f"        add_header Strict-Transport-Security \"max-age={max_age};\" always;"]


def render_dynamic_protection_headers(site: dict) -> list[str]:
    dynamic = site_bot_protection(site).get("dynamicProtection") or {}
    if not dynamic.get("enabled"):
        return []
    enabled_parts = [
        name
        for name, enabled in (
            ("html", dynamic.get("html")),
            ("js", dynamic.get("js")),
            ("watermark", dynamic.get("watermark")),
        )
        if enabled
    ]
    value = ",".join(enabled_parts) or "on"
    return [
        f"        add_header X-FreeWAF-Dynamic-Protection \"{value}\" always;",
        "        add_header Cache-Control \"no-transform\" always;",
    ]


def render_bot_replay_limit(site: dict) -> list[str]:
    if not site_bot_protection(site).get("antiReplay"):
        return []
    return [f"        limit_req zone={bot_replay_zone_name(site)} burst=1 nodelay;"]


def render_proxy_ssl(upstream_scheme: str, proxy: dict) -> list[str]:
    if upstream_scheme != "https" or not proxy.get("proxySslServerName"):
        return []
    return [
        "        proxy_ssl_server_name on;",
        "        proxy_ssl_name $host;",
    ]


def render_acl_limit_zones(sites: list[dict]) -> list[str]:
    zones = []
    for site in sites:
        limit = active_acl_access_limit(site)
        if not limit:
            continue
        if acl_limit_uses_mapped_key(site, limit):
            zones.extend(render_acl_limit_key_maps(site, limit))
        zones.append(
            f"limit_req_zone {acl_limit_key(site, limit)} zone={acl_zone_name(site)}:10m rate={nginx_acl_rate(limit)};"
        )
        if site_features(site).get("httpFlood"):
            zones.append(
                f"limit_req_zone {acl_fingerprint_limit_key(site, limit)} zone={acl_fingerprint_zone_name(site)}:10m rate={nginx_acl_rate(limit)};"
            )
    return zones


def render_acl_limit_key_maps(site: dict, limit: dict) -> list[str]:
    challenge = acl_limit_action(limit) == "challenge_v1"
    verified_bypass = site_verified_search_bots(site).get("bypassRateLimit")
    if challenge and verified_bypass:
        return [
            f'map "$sfl_verified_search_bot:$cookie_freewaf_challenge" ${acl_key_name(site)} {{',
            "    default $binary_remote_addr;",
            '    ~^1: "";',
            '    "0:passed" "";',
            "}",
            "",
            f'map "$sfl_verified_search_bot:$cookie_freewaf_challenge" ${acl_fingerprint_key_name(site)} {{',
            '    default "$remote_addr|$request_method|$http_user_agent";',
            '    ~^1: "";',
            '    "0:passed" "";',
            "}",
            "",
        ]
    if challenge:
        return [
            f"map $cookie_freewaf_challenge ${acl_key_name(site)} {{",
            "    default $binary_remote_addr;",
            "    passed \"\";",
            "}",
            "",
            f"map $cookie_freewaf_challenge ${acl_fingerprint_key_name(site)} {{",
            "    default \"$remote_addr|$request_method|$http_user_agent\";",
            "    passed \"\";",
            "}",
            "",
        ]
    if verified_bypass:
        return [
            f"map $sfl_verified_search_bot ${acl_key_name(site)} {{",
            "    default $binary_remote_addr;",
            '    1 "";',
            "}",
            "",
            f"map $sfl_verified_search_bot ${acl_fingerprint_key_name(site)} {{",
            '    default "$remote_addr|$request_method|$http_user_agent";',
            '    1 "";',
            "}",
            "",
        ]
    return []


def active_acl_access_limit(site: dict) -> dict | None:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    limit = acl.get("accessLimit") if isinstance(acl.get("accessLimit"), dict) else {}
    if not acl.get("enabled") or not limit.get("enabled") or acl_rate_limit_mode(site) == "global":
        return None
    return limit


def acl_rate_limit_mode(site: dict) -> str:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    mode = str(acl.get("rateLimitMode") or "custom").lower()
    return mode if mode in {"global", "custom"} else "custom"


def acl_waiting_room(site: dict) -> bool:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    return bool(acl.get("waitingRoom"))


def acl_zone_name(site: dict) -> str:
    return f"sfl_acl_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def acl_fingerprint_zone_name(site: dict) -> str:
    return f"{acl_zone_name(site)}_fp"


def acl_key_name(site: dict) -> str:
    return f"sfl_acl_key_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def acl_fingerprint_key_name(site: dict) -> str:
    return f"{acl_key_name(site)}_fp"


def acl_limit_key(site: dict, limit: dict) -> str:
    if acl_limit_uses_mapped_key(site, limit):
        return f"${acl_key_name(site)}"
    return "$binary_remote_addr"


def acl_fingerprint_limit_key(site: dict, limit: dict) -> str:
    if acl_limit_uses_mapped_key(site, limit):
        return f"${acl_fingerprint_key_name(site)}"
    return "\"$remote_addr|$request_method|$http_user_agent\""


def acl_limit_uses_mapped_key(site: dict, limit: dict) -> bool:
    return acl_limit_action(limit) == "challenge_v1" or bool(site_verified_search_bots(site).get("bypassRateLimit"))


def acl_limit_action(limit: dict | None) -> str:
    action = str((limit or {}).get("action") or "block").lower()
    return action if action in {"allow", "block", "challenge_v1", "monitor"} else "block"


def any_uses_challenge(sites: list[dict]) -> bool:
    return any(site_uses_challenge(site) for site in sites)


def site_uses_challenge(site: dict) -> bool:
    return bool(
        site_bot_protection(site).get("antiBotChallenge")
        or acl_limit_action(active_acl_access_limit(site)) == "challenge_v1"
        or site_under_attack(site).get("enabled")
    )


def nginx_acl_rate(limit: dict) -> str:
    count = max(1, int(limit.get("count") or 200))
    period = max(1, int(limit.get("period") or 10))
    per_minute = max(1, round(count * 60 / period))
    if per_minute < 60:
        return f"{per_minute}r/m"
    return f"{max(1, round(count / period))}r/s"


def site_features(site: dict) -> dict:
    features = site.get("features") if isinstance(site.get("features"), dict) else {}
    return {
        "httpFlood": features.get("httpFlood") is not False,
        "botProtection": features.get("botProtection") is not False,
        "geoBlock": bool(features.get("geoBlock")),
    }


def site_geo_block(site: dict) -> dict:
    features = site_features(site)
    source = site.get("geoBlock") if isinstance(site.get("geoBlock"), dict) else {}
    countries = []
    for item in source.get("countries") or []:
        code = str(item or "").strip().upper()
        if re.match(r"^[A-Z]{2}$", code) and code not in countries:
            countries.append(code)
    action = str(source.get("action") or "block").lower()
    if action not in {"block", "monitor"}:
        action = "block"
    enabled = features["geoBlock"] and source.get("enabled") is not False and bool(countries)
    return {"enabled": enabled, "countries": countries, "action": action}


def geo_block_var_name(site: dict) -> str:
    return f"sfl_geo_block_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def site_bot_protection(site: dict) -> dict:
    features = site_features(site)
    source = site.get("botProtection") if isinstance(site.get("botProtection"), dict) else {}
    dynamic = source.get("dynamicProtection") if isinstance(source.get("dynamicProtection"), dict) else {}
    anti_replay = source.get("antiReplay") if isinstance(source.get("antiReplay"), dict) else {}
    verified = source.get("verifiedSearchBots") if isinstance(source.get("verifiedSearchBots"), dict) else {}
    enabled = features["botProtection"] and source.get("enabled") is not False
    anti_bot = enabled and source.get("antiBotChallenge") is not False
    login = source.get("loginChallenge") if isinstance(source.get("loginChallenge"), dict) else {}
    rate = source.get("rateChallenge") if isinstance(source.get("rateChallenge"), dict) else {}
    login_patterns = [str(item).strip() for item in (login.get("pathPatterns") or DEFAULT_BOT_LOGIN_PATH_PATTERNS) if str(item).strip()]
    challenge_count = max(1, parse_int(rate.get("challengeCount")) or DEFAULT_BOT_RATE_CHALLENGE["challengeCount"])
    block_count = max(challenge_count + 1, parse_int(rate.get("blockCount")) or DEFAULT_BOT_RATE_CHALLENGE["blockCount"])
    block_minutes = parse_int(rate.get("blockMinutes") or rate.get("blockMin")) or DEFAULT_BOT_RATE_CHALLENGE["blockMinutes"]
    if block_minutes not in {10, 30, 60}:
        block_minutes = DEFAULT_BOT_RATE_CHALLENGE["blockMinutes"]
    dynamic_enabled = enabled and bool(dynamic.get("enabled"))
    return {
        "enabled": enabled,
        "antiBotChallenge": anti_bot,
        "verifiedSearchBots": {
            "enabled": anti_bot and verified.get("enabled") is not False,
            "bypassChallenge": verified.get("bypassChallenge") is not False,
            "bypassRateLimit": verified.get("bypassRateLimit") is not False,
        },
        "loginChallenge": {
            "enabled": anti_bot and login.get("enabled") is not False and bool(login_patterns),
            "pathPatterns": login_patterns[:64],
        },
        "rateChallenge": {
            "enabled": anti_bot and bool(rate.get("enabled", DEFAULT_BOT_RATE_CHALLENGE["enabled"])),
            "windowSeconds": bot_rate_window_seconds(rate),
            "challengeCount": challenge_count,
            "blockCount": block_count,
            "blockMinutes": block_minutes,
        },
        "dynamicProtection": {
            "enabled": dynamic_enabled,
            "html": dynamic_enabled and bool(dynamic.get("html")),
            "js": dynamic_enabled and bool(dynamic.get("js")),
            "watermark": dynamic_enabled and bool(dynamic.get("watermark")),
        },
        "antiReplay": enabled and bool(anti_replay.get("enabled")),
    }


def site_under_attack(site: dict) -> dict:
    source = site.get("underAttack") if isinstance(site.get("underAttack"), dict) else {}
    return {"enabled": bool(source.get("enabled"))}


def site_verified_search_bots(site: dict) -> dict:
    protection = site_bot_protection(site)
    config = protection.get("verifiedSearchBots") if isinstance(protection.get("verifiedSearchBots"), dict) else {}
    return {
        "enabled": bool(config.get("enabled")),
        "bypassChallenge": bool(config.get("enabled") and config.get("bypassChallenge")),
        "bypassRateLimit": bool(config.get("enabled") and config.get("bypassRateLimit")),
    }


def any_verified_bot_rate_bypass(sites: list[dict]) -> bool:
    return any(site_verified_search_bots(site).get("bypassRateLimit") for site in sites)


def bot_replay_zone_name(site: dict) -> str:
    return f"sfl_replay_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def bot_replay_key_name(site: dict) -> str:
    return f"{bot_replay_zone_name(site)}_key"


def should_emit_rule_for_site(rule: dict, site: dict) -> bool:
    features = site_features(site)
    if rule.get("id") in BOT_RULE_IDS:
        return features["botProtection"]
    return True


def render_bot_protection(site: dict) -> list[str]:
    protection = site_bot_protection(site)
    if not protection.get("antiBotChallenge"):
        return []

    effect = "monitor" if site.get("mode") == "monitor" else "block"
    login = protection.get("loginChallenge") or {}
    login_patterns = login.get("pathPatterns") or []
    login_regex = any_regex(login_patterns) if login.get("enabled") and login_patterns else ""
    lines = [
        "    set $sfl_bot_block 0;",
        "    set $sfl_bot_challenge 0;",
        "    if ($sfl_bad_bot_ua = 1) {",
        "        set $sfl_bot_block 1;",
        "    }",
        "    if ($sfl_bad_referer = 1) {",
        "        set $sfl_bot_block 1;",
        "    }",
        "    if ($sfl_unsafe_method = 1) {",
        "        set $sfl_bot_block 1;",
        "    }",
    ]
    if login_regex:
        lines.extend(
            [
                f"    if ($request_uri ~* {nginx_regex(login_regex)}) {{",
                "        set $sfl_bot_challenge 1;",
                "    }",
            ]
        )
    lines.extend(
        [
            "    if ($sfl_challenge_passed = 1) {",
            "        set $sfl_bot_challenge 0;",
            "    }",
            *(
                [
                    "    if ($sfl_verified_search_bot = 1) {",
                    "        set $sfl_bot_challenge 0;",
                    "    }",
                ]
                if site_verified_search_bots(site).get("bypassChallenge")
                else []
            ),
            "    if ($sfl_allow = 1) {",
            "        set $sfl_bot_block 0;",
            "        set $sfl_bot_challenge 0;",
            "    }",
            "    if ($sfl_block = 1) {",
            "        set $sfl_bot_block 0;",
            "        set $sfl_bot_challenge 0;",
            "    }",
        ]
    )

    if effect == "monitor":
        lines.extend(
            [
                "    if ($sfl_bot_block = 1) {",
                "        set $sfl_verdict monitor;",
                "        set $sfl_reason \"Bot protection matched scanner headers\";",
                "    }",
                "    if ($sfl_bot_challenge = 1) {",
                "        set $sfl_verdict monitor;",
                "        set $sfl_reason \"Bot protection protected login path\";",
                "    }",
                "",
            ]
        )
        return lines

    lines.extend(
        [
            "    if ($sfl_bot_block = 1) {",
            "        set $sfl_block 1;",
            "        set $sfl_verdict block;",
            "        set $sfl_reason \"Bot protection matched scanner headers\";",
            "    }",
            "    if ($sfl_bot_challenge = 1) {",
            "        set $sfl_challenge 1;",
            "        set $sfl_verdict challenge;",
            "        set $sfl_reason \"Bot protection protected login path\";",
            "    }",
            "",
        ]
    )
    return lines


def render_under_attack_protection(site: dict) -> list[str]:
    if not site_under_attack(site).get("enabled"):
        return []
    return [
        "    set $sfl_under_attack_challenge 1;",
        "    if ($sfl_under_attack_bypass = 1) {",
        "        set $sfl_under_attack_challenge 0;",
        "    }",
        "    if ($sfl_challenge_passed = 1) {",
        "        set $sfl_under_attack_challenge 0;",
        "    }",
        *(
            [
                "    if ($sfl_verified_search_bot = 1) {",
                "        set $sfl_under_attack_challenge 0;",
                "    }",
            ]
            if site_verified_search_bots(site).get("bypassChallenge")
            else []
        ),
        "    if ($sfl_allow = 1) {",
        "        set $sfl_under_attack_challenge 0;",
        "    }",
        "    if ($sfl_block = 1) {",
        "        set $sfl_under_attack_challenge 0;",
        "    }",
        "    if ($sfl_under_attack_challenge = 1) {",
        "        set $sfl_challenge 1;",
        "        set $sfl_verdict challenge;",
        "        set $sfl_reason \"Under Attack Mode browser challenge\";",
        "    }",
        "",
    ]


def render_geo_block(site: dict) -> list[str]:
    config = site_geo_block(site)
    if not config.get("enabled"):
        return []

    effect = "monitor" if site.get("mode") == "monitor" or config.get("action") == "monitor" else "block"
    match_var = "$sfl_geo_block_hit"
    reason = nginx_string(f"Geo block matched country: {', '.join(config.get('countries') or [])}")
    lines = [
        f"    set {match_var} 0;",
        f"    if (${geo_block_var_name(site)} = 1) {{",
        f"        set {match_var} 1;",
        "    }",
        "    if ($sfl_allow = 1) {",
        f"        set {match_var} 0;",
        "    }",
        "    if ($sfl_block = 1) {",
        f"        set {match_var} 0;",
        "    }",
    ]

    if effect == "monitor":
        lines.extend(
            [
                f"    if ({match_var} = 1) {{",
                "        set $sfl_verdict monitor;",
                f"        set $sfl_reason \"{reason}\";",
                "    }",
                "",
            ]
        )
        return lines

    lines.extend(
        [
            f"    if ({match_var} = 1) {{",
            "        set $sfl_block 1;",
            "        set $sfl_verdict block;",
            f"        set $sfl_reason \"{reason}\";",
            "    }",
            "",
        ]
    )
    return lines


def render_access_rule_if(rule: dict, access_index: int, effect: str, rule_index: int, state: dict) -> list[str]:
    match_var = f"$sfl_rule_{rule_index}"
    reason = nginx_string(rule.get("name") or rule.get("id") or "Access rule matched")
    condition_groups = access_condition_groups(rule, access_index, state)

    if not condition_groups:
        return [
            f"    # Access rule {nginx_comment(rule.get('name'))} has no active Nginx-native conditions.",
            "",
        ]

    lines = [f"    set {match_var} 0;"]
    for group_index, conditions in enumerate(condition_groups, start=1):
        token_name = f"sfl_access_{rule_index}_{group_index}"
        token_var = f"${token_name}"
        group_var = f"$sfl_access_{rule_index}_group_{group_index}"
        expected = "1" * len(conditions)
        lines.extend(
            [
                f"    set {token_var} \"\";",
                f"    set {group_var} 0;",
            ]
        )
        for condition in conditions:
            lines.extend(
                [
                    f"    if ({condition}) {{",
                    f"        set {token_var} \"${{{token_name}}}1\";",
                    "    }",
                ]
            )
        lines.extend(
            [
                f"    if ({token_var} = \"{expected}\") {{",
                f"        set {group_var} 1;",
                "    }",
                f"    if ({group_var} = 1) {{",
                f"        set {match_var} 1;",
                "    }",
            ]
        )

    if effect == "allow":
        if rule.get("continueDetect"):
            lines.extend(
                [
                    f"    if ({match_var} = 1) {{",
                    "        set $sfl_verdict allow;",
                    f"        set $sfl_reason \"Allowed by {reason}\";",
                    "    }",
                ]
            )
            return lines

        lines.extend(
            [
                f"    if ({match_var} = 1) {{",
                "        set $sfl_allow 1;",
                "        set $sfl_block 0;",
                "        set $sfl_verdict allow;",
                f"        set $sfl_reason \"Allowed by {reason}\";",
                "    }",
            ]
        )
        return lines

    verdict = "monitor" if effect == "monitor" else "block"
    block_value = "0" if effect == "monitor" else "1"
    lines.extend(
        [
            "    if ($sfl_allow = 1) {",
            f"        set {match_var} 0;",
            "    }",
            f"    if ({match_var} = 1) {{",
            f"        set $sfl_block {block_value};",
            f"        set $sfl_verdict {verdict};",
            f"        set $sfl_reason \"{reason}\";",
            "    }",
        ]
    )
    return lines


def access_condition_groups(rule: dict, access_index: int, state: dict) -> list[list[str]]:
    condition_groups = rule.get("conditionGroups") if isinstance(rule.get("conditionGroups"), list) else []
    if condition_groups:
        groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
        rendered_groups = []
        for group_index, condition_group in enumerate(condition_groups, start=1):
            rendered_conditions = []
            for condition_index, condition in enumerate(condition_group.get("conditions") or [], start=1):
                rendered = access_condition_expression(condition, access_index, group_index, condition_index, groups)
                if rendered:
                    rendered_conditions.append(rendered)
            if rendered_conditions:
                rendered_groups.append(rendered_conditions)
        return rendered_groups

    legacy_conditions = legacy_access_conditions(rule, access_index, state)
    return [legacy_conditions] if legacy_conditions else []


def legacy_access_conditions(rule: dict, access_index: int, state: dict) -> list[str]:
    groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
    conditions = []
    if collect_access_ips(rule, groups):
        conditions.append(f"$sfl_access_ip_{access_index} = 1")
    if rule.get("methods"):
        conditions.append(f"$request_method ~* {nginx_regex(exact_any_regex(rule['methods']))}")
    if rule.get("uriPatterns"):
        conditions.append(f"$request_uri ~* {nginx_regex(any_regex(rule['uriPatterns']))}")
    if rule.get("hostPatterns"):
        conditions.append(f"$host ~* {nginx_regex(any_regex(rule['hostPatterns']))}")
    if rule.get("userAgentPatterns"):
        conditions.append(f"$http_user_agent ~* {nginx_regex(any_regex(rule['userAgentPatterns']))}")
    return conditions


def access_condition_expression(condition: dict, access_index: int, group_index: int, condition_index: int, groups: dict[str, dict]) -> str | None:
    target = str(condition.get("target") or "source_ip")
    operator = str(condition.get("operator") or "equals")
    content = str(condition.get("content") or "")

    if target == "source_ip":
        if operator in {"cidr", "not_cidr", "in_ip_group", "not_in_ip_group"}:
            items = collect_condition_ip_items(condition, groups)
            if not items:
                return None
            expected = "0" if operator in {"not_cidr", "not_in_ip_group"} else "1"
            return f"${access_condition_geo_var(access_index, group_index, condition_index)} = {expected}"
        regex = exact_regex(content)
        negate = "!" if operator == "not_equals" else ""
        return f"$remote_addr {negate}~* {nginx_regex(regex)}"

    variable = access_condition_variable(target)
    if not variable:
        return None

    if operator == "equals":
        return f"{variable} ~* {nginx_regex(exact_regex(content))}"
    if operator == "not_equals":
        return f"{variable} !~* {nginx_regex(exact_regex(content))}"
    if operator == "contains":
        return f"{variable} ~* {nginx_regex(re.escape(content))}"
    if operator == "not_contains":
        return f"{variable} !~* {nginx_regex(re.escape(content))}"
    if operator == "regex":
        return f"{variable} ~* {nginx_regex(content)}"
    if operator == "not_regex":
        return f"{variable} !~* {nginx_regex(content)}"
    return None


def access_condition_variable(target: str) -> str | None:
    if target == "source_ip":
        return "$remote_addr"
    if target == "uri":
        return "$request_uri"
    if target == "host":
        return "$host"
    if target == "user_agent":
        return "$http_user_agent"
    if target == "method":
        return "$request_method"
    return None


def access_condition_geo_var(access_index: int, group_index: int, condition_index: int) -> str:
    return f"sfl_access_ip_{access_index}_{group_index}_{condition_index}"


def collect_condition_ip_items(condition: dict, groups: dict[str, dict]) -> list[str]:
    target = str(condition.get("target") or "")
    operator = str(condition.get("operator") or "")
    content = str(condition.get("content") or "")
    if target != "source_ip":
        return []
    if operator in {"cidr", "not_cidr"}:
        return [content] if content else []
    if operator in {"in_ip_group", "not_in_ip_group"}:
        return ip_group_items(groups.get(content, {}))
    return []


def collect_access_ips(rule: dict, groups: dict[str, dict]) -> list[str]:
    items = list(rule.get("ips") or [])
    for group_id in rule.get("ipGroupIds") or []:
        items.extend(ip_group_items(groups.get(group_id, {})))
    return list(dict.fromkeys(items))


def ip_group_items(group: dict | None) -> list[str]:
    if not group:
        return []
    items = list(group.get("items") or [])
    item_file = str(group.get("itemsFile") or "").strip()
    if item_file:
        path = Path(item_file)
        if path.exists() and path.is_file():
            file_items = [line.strip() for line in path.read_text(encoding="utf-8", errors="replace").splitlines() if line.strip()]
            items.extend(file_items)
    return list(dict.fromkeys(items))


def render_rule_if(rule: dict, effect: str, index: int) -> list[str]:
    target = str(rule.get("target") or "all")
    if target == "body":
        return [
            f"    # Rule {nginx_comment(rule.get('name'))} targets request body.",
            "    # Native Nginx cannot inspect request bodies here; use ModSecurity, Lua, or njs for body rules.",
            "",
        ]

    variables = target_variables(target)
    pattern = nginx_regex(rule.get("pattern") or "")
    reason = nginx_string(rule.get("name") or rule.get("id") or "Rule matched")
    match_var = f"$sfl_rule_{index}"
    lines = [f"    set {match_var} 0;"]
    for variable in variables:
        lines.extend(
            [
                f"    if ({variable} ~* {pattern}) {{",
                f"        set {match_var} 1;",
                "    }",
            ]
        )

    if effect == "allow":
        lines.extend(
            [
                f"    if ({match_var} = 1) {{",
                "        set $sfl_allow 1;",
                "        set $sfl_block 0;",
                "        set $sfl_verdict allow;",
                f"        set $sfl_reason \"Allowed by {reason}\";",
                "    }",
            ]
        )
        return lines

    verdict = "monitor" if effect == "monitor" else "block"
    block_value = "0" if effect == "monitor" else "1"
    lines.extend(
        [
            "    if ($sfl_allow = 1) {",
            f"        set {match_var} 0;",
            "    }",
            f"    if ({match_var} = 1) {{",
            f"        set $sfl_block {block_value};",
            f"        set $sfl_verdict {verdict};",
            f"        set $sfl_reason \"{reason}\";",
            "    }",
        ]
    )
    return lines


def target_variables(target: str) -> list[str]:
    if target == "url":
        return ["$request_uri"]
    if target == "method":
        return ["$request_method"]
    if target == "ip":
        return ["$remote_addr"]
    if target == "headers":
        return ["$http_user_agent", "$http_referer", "$http_content_type"]
    return ["$request_method", "$request_uri", "$http_user_agent", "$http_referer", "$remote_addr"]


def render_rate_limit(state: dict, site: dict) -> list[str]:
    waiting_room = acl_waiting_room(site)
    acl_limit = active_acl_access_limit(site)
    if acl_limit:
        burst = max(1, int(acl_limit.get("count") or 200))
        lines = [render_limit_req_directive(acl_zone_name(site), burst, waiting_room)]
        if site_features(site).get("httpFlood"):
            lines.append(render_limit_req_directive(acl_fingerprint_zone_name(site), burst, waiting_room))
        if acl_limit_action(acl_limit) == "monitor":
            lines.append("        limit_req_dry_run on;")
        return lines

    rate_limit = state.get("settings", {}).get("rateLimit", {})
    if not rate_limit.get("enabled") or not site_features(site).get("httpFlood"):
        return []
    burst = max(1, int(rate_limit.get("max") or 120))
    return [
        render_limit_req_directive("freewaf_rate", burst, waiting_room),
        render_limit_req_directive("freewaf_rate_fingerprint", burst, waiting_room),
    ]


def render_limit_req_directive(zone: str, burst: int, waiting_room: bool) -> str:
    suffix = "" if waiting_room else " nodelay"
    return f"        limit_req zone={zone} burst={burst}{suffix};"


def render_rate_limit_error_page(site: dict) -> list[str]:
    acl_limit = active_acl_access_limit(site)
    if acl_limit_action(acl_limit) == "challenge_v1":
        return ["    error_page 429 = @freewaf_challenge;"]
    return ["    error_page 429 = @freewaf_rate_limited;"]


def nginx_rate(rate_limit: dict) -> str:
    maximum = max(1, int(rate_limit.get("max") or 120))
    window_ms = max(1000, int(rate_limit.get("windowMs") or 60000))
    per_minute = max(1, round(maximum * 60000 / window_ms))
    return f"{per_minute}r/m"


def escape_server_name(value: str) -> str:
    safe = str(value or "_").replace(";", "").replace("{", "").replace("}", "").strip()
    if safe == "*":
        return "_"
    return safe or "_"


def nginx_regex(value: str) -> str:
    escaped = str(value).replace("\n", " ").replace("\r", " ").replace('"', '\\"')
    return f'"{escaped}"'


def any_regex(values: list[str]) -> str:
    return "(?:" + "|".join(str(value).replace("\n", " ").replace("\r", " ") for value in values if str(value).strip()) + ")"


def exact_regex(value: str) -> str:
    return "^" + re.escape(str(value or "")) + "$"


def exact_any_regex(values: list[str]) -> str:
    escaped = [str(value).replace("\\", "\\\\").replace(".", "\\.") for value in values if str(value).strip()]
    return "^(?:" + "|".join(escaped) + ")$"


def nginx_path(value: str) -> str:
    return str(value).replace("\\", "/").replace(";", "").replace("{", "").replace("}", "")


def nginx_value(value: str) -> str:
    return str(value or "").replace("\x00", "").replace(";", "").replace("{", "").replace("}", "").replace("\n", " ")


def nginx_string(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"').replace(";", "")


def nginx_comment(value: str) -> str:
    return str(value or "").replace("\n", " ").replace("\r", " ")


def safe_identifier(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", str(value or "site"))
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe[:48] or "site"


def block_page(site: dict) -> str:
    title = "Request blocked"
    message = f"FreeWAF blocked this request for {site.get('name', 'this site')}."
    return error_page_html(title, message)


def rate_limit_page(site: dict) -> str:
    title = "Request limited"
    message = f"FreeWAF rate-limited this request for {site.get('name', 'this site')}."
    return error_page_html(title, message)


def challenge_page(site: dict) -> str:
    title = "Security check"
    message = f"FreeWAF is verifying this browser for {site.get('name', 'this site')}."
    html = (
        "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{title}</title>"
        "<style>body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:#f5f7f8;color:#17202a;display:grid;min-height:100vh;place-items:center}"
        "main{width:min(560px,calc(100vw - 32px));background:#fff;border:1px solid #d8e0ea;border-radius:8px;padding:28px}"
        "h1{margin:0 0 12px;font-size:24px}p{line-height:1.55;margin:0;color:#526071}</style></head>"
        f"<body><main><h1>{title}</h1><p>{message}</p><noscript><p>JavaScript is required to continue.</p></noscript></main>"
        "<script>(function(){document.cookie=\"freewaf_challenge=passed; Max-Age=1800; Path=/; SameSite=Lax\";window.location.replace(window.location.href);})();</script>"
        "</body></html>"
    )
    return html.replace("\\", "\\\\").replace("'", "\\'")


def error_page_html(title: str, message: str) -> str:
    html = (
        "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{title}</title>"
        "<style>body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:#f5f7f8;color:#17202a;display:grid;min-height:100vh;place-items:center}"
        "main{width:min(560px,calc(100vw - 32px));background:#fff;border:1px solid #d8e0ea;border-radius:8px;padding:28px}"
        "h1{margin:0 0 12px;font-size:24px}p{line-height:1.55;margin:0;color:#526071}</style></head>"
        f"<body><main><h1>{title}</h1><p>{message}</p></main></body></html>"
    )
    return html.replace("\\", "\\\\").replace("'", "\\'")


def parse_int(value) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def chunks(items: list[str], size: int) -> list[list[str]]:
    width = max(1, size)
    return [items[index : index + width] for index in range(0, len(items), width)]
