from __future__ import annotations

import os
import json
import re
import shlex
import subprocess
from pathlib import Path
from urllib.parse import urlparse


NATIVE_TARGETS = {"all", "url", "headers", "method", "ip"}
BOT_RULE_IDS = {"builtin-scanner-agent"}
BOT_BLOCK_UA_PATTERN = (
    r"(?:sqlmap|nikto|acunetix|nessus|nuclei|wpscan|masscan|nmap|zgrab|gobuster|"
    r"dirbuster|ffuf|jaeles|zmeu|commix|havij|netsparker|openvas|arachni)"
)
BOT_CHALLENGE_UA_PATTERN = (
    r"(?:curl|wget|python-requests|python-urllib|aiohttp|httpx|scrapy|libwww-perl|"
    r"go-http-client|java/|okhttp|apache-httpclient|node-fetch|axios|perl|ruby|"
    r"bot|crawler|spider|headlesschrome|phantomjs|selenium|playwright|puppeteer)"
)
GOOD_BOT_UA_PATTERN = (
    r"(?:googlebot|bingbot|duckduckbot|baiduspider|yandexbot|facebookexternalhit|"
    r"meta-externalagent|facebot|slurp)"
)


def nginx_output_file(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_OUTPUT_FILE", "./nginx/generated/freewaf.conf"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_site_config_dir(root_dir: Path) -> Path:
    configured = os.environ.get("NGINX_SITE_CONF_DIR", "").strip()
    if configured:
        path = Path(configured)
        return path if path.is_absolute() else root_dir / path
    return nginx_output_file(root_dir).parent / "sites"


def nginx_access_log_file(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_ACCESS_LOG", "./logs/freewaf_access.log"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_access_log_directive() -> str:
    configured = os.environ.get("NGINX_ACCESS_LOG", "./logs/freewaf_access.log")
    return configured.replace("\\", "/")


def nginx_site_log_dir(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_SITE_LOG_DIR", "./logs/freewaf"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_site_log_dir_directive() -> str:
    return os.environ.get("NGINX_SITE_LOG_DIR", "./logs/freewaf").replace("\\", "/").rstrip("/")


def nginx_site_access_log_directive(site: dict) -> str:
    return f"{nginx_site_log_dir_directive()}/accesslog_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def nginx_site_error_log_directive(site: dict) -> str:
    return f"{nginx_site_log_dir_directive()}/errorlog_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def generate_nginx_config(state: dict) -> str:
    blocks = generate_nginx_common_blocks(state)
    site_configs = render_domain_config_files(state)
    if not site_configs:
        blocks.append("# No enabled sites.")
    else:
        blocks.extend(site_configs.values())
    return "\n\n".join(blocks) + "\n"


def generate_nginx_common_blocks(state: dict) -> list[str]:
    enabled_sites = [site for site in state.get("sites", []) if site.get("enabled")]
    enabled_access_rules = [rule for rule in state.get("accessRules", []) if rule.get("enabled")]
    blocks = [
        "# Generated by FreeWAF. Do not edit by hand.",
        "# Include this file inside the nginx http {} context.",
        "",
        "map $request_uri $sfl_verdict {",
        "    default allow;",
        "}",
        "",
        "map $request_uri $sfl_reason {",
        "    default \"Allowed\";",
        "}",
        "",
        "log_format freewaf escape=json '{\"time\":\"$time_iso8601\",\"remote_addr\":\"$remote_addr\",\"host\":\"$host\",\"method\":\"$request_method\",\"uri\":\"$request_uri\",\"status\":$status,\"bytes\":$body_bytes_sent,\"request_time\":$request_time,\"upstream_status\":\"$upstream_status\",\"verdict\":\"$sfl_verdict\",\"reason\":\"$sfl_reason\",\"user_agent\":\"$http_user_agent\",\"referer\":\"$http_referer\"}';",
        "",
        "map $http_upgrade $sfl_connection_upgrade {",
        "    default upgrade;",
        "    '' close;",
        "}",
        "",
    ]

    if any(site_bot_protection(site).get("antiBotChallenge") for site in enabled_sites):
        blocks.extend(render_bot_detection_maps())

    if any_uses_challenge(enabled_sites):
        blocks.extend(render_challenge_maps())

    bot_zones = render_bot_limit_zones(enabled_sites)
    if bot_zones:
        blocks.extend(bot_zones)

    rate_limit = state.get("settings", {}).get("rateLimit", {})
    uses_global_rate = any(
        site_features(site).get("httpFlood") and not active_acl_access_limit(site)
        for site in enabled_sites
    )
    if rate_limit.get("enabled") and uses_global_rate:
        blocks.extend(render_global_rate_limit_zones(rate_limit))

    acl_zones = render_acl_limit_zones(enabled_sites)
    if acl_zones:
        blocks.extend(acl_zones)

    if (rate_limit.get("enabled") and uses_global_rate) or acl_zones or bot_zones:
        blocks.extend(["limit_req_status 429;", ""])

    access_maps = render_access_maps(state, enabled_access_rules)
    if access_maps:
        blocks.extend(access_maps)
        blocks.append("")

    return blocks


def render_domain_config_files(state: dict) -> dict[str, str]:
    enabled_sites = [site for site in state.get("sites", []) if site.get("enabled")]
    certificates = {certificate["id"]: certificate for certificate in state.get("certificates", [])}
    configs = {}
    for site in enabled_sites:
        for hostname in site_hostnames(site):
            filename = domain_config_filename(site, hostname)
            configs[filename] = render_site_server(site, state, certificates, hostname)
    return configs


def write_nginx_config(root_dir: Path, state: dict) -> Path:
    output_file = nginx_output_file(root_dir)
    site_config_dir = nginx_site_config_dir(root_dir)
    site_configs = render_domain_config_files(state)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    site_config_dir.mkdir(parents=True, exist_ok=True)
    nginx_site_log_dir(root_dir).mkdir(parents=True, exist_ok=True)

    for stale_file in site_config_dir.glob("*.conf"):
        if stale_file.is_file():
            stale_file.unlink()

    for filename, content in site_configs.items():
        (site_config_dir / filename).write_text(content, encoding="utf-8")

    blocks = generate_nginx_common_blocks(state)
    if site_configs:
        blocks.append(f"include {nginx_path(str(site_config_dir / '*.conf'))};")
    else:
        blocks.append("# No enabled sites.")
    output_file.write_text("\n\n".join(blocks) + "\n", encoding="utf-8")
    return output_file


def run_nginx_command(command: str | None) -> dict:
    if not command:
        return {"configured": False, "ok": False, "stdout": "", "stderr": "No command configured"}

    completed = subprocess.run(
        shlex.split(command),
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    return {
        "configured": True,
        "ok": completed.returncode == 0,
        "returnCode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def nginx_runtime(root_dir: Path) -> dict:
    return {
        "outputFile": str(nginx_output_file(root_dir)),
        "siteConfigDir": str(nginx_site_config_dir(root_dir)),
        "accessLog": str(nginx_access_log_file(root_dir)),
        "siteLogDir": str(nginx_site_log_dir(root_dir)),
        "certDir": str(nginx_cert_dir(root_dir)),
        "testCommand": os.environ.get("NGINX_TEST_CMD", "nginx -t"),
        "reloadCommand": os.environ.get("NGINX_RELOAD_CMD", "nginx -s reload"),
    }


def nginx_cert_dir(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_CERT_DIR", "./nginx/certs"))
    return configured if configured.is_absolute() else root_dir / configured


def parse_nginx_logs(root_dir: Path, limit: int = 500) -> list[dict]:
    log_files = [nginx_access_log_file(root_dir)]
    site_log_dir = nginx_site_log_dir(root_dir)
    if site_log_dir.exists():
        log_files.extend(sorted(site_log_dir.glob("accesslog_*")))

    entries = []
    for log_file in log_files:
        if not log_file.exists() or not log_file.is_file():
            continue
        lines = log_file.read_text(encoding="utf-8", errors="replace").splitlines()
        for index, line in enumerate(reversed(lines[-limit:])):
            try:
                raw = json.loads(line)
            except json.JSONDecodeError:
                continue

            verdict = str(raw.get("verdict") or "allow")
            status = parse_int(raw.get("status"))
            reason = str(raw.get("reason") or ("Blocked by Nginx WAF" if verdict == "block" else "Allowed"))
            entries.append(
                {
                    "id": f"nginx-{safe_identifier(log_file.name)}-{len(lines) - index}",
                    "at": str(raw.get("time") or ""),
                    "siteId": None,
                    "siteName": str(raw.get("host") or "Nginx"),
                    "host": str(raw.get("host") or ""),
                    "method": str(raw.get("method") or ""),
                    "path": str(raw.get("uri") or ""),
                    "ip": str(raw.get("remote_addr") or ""),
                    "verdict": verdict,
                    "statusCode": status,
                    "upstreamStatus": parse_int(raw.get("upstream_status")),
                    "durationMs": int(float(raw.get("request_time") or 0) * 1000),
                    "reason": reason,
                    "matchedRules": [{"name": reason, "severity": "medium", "action": verdict}] if verdict != "allow" else [],
                    "userAgent": str(raw.get("user_agent") or ""),
                    "referer": str(raw.get("referer") or ""),
                    "requestSize": 0,
                }
            )

    return sorted(entries, key=lambda entry: entry.get("at") or "", reverse=True)[:limit]


def clear_nginx_logs(root_dir: Path) -> None:
    log_files = [nginx_access_log_file(root_dir)]
    site_log_dir = nginx_site_log_dir(root_dir)
    if site_log_dir.exists():
        log_files.extend(sorted(site_log_dir.glob("accesslog_*")))
    for log_file in log_files:
        if log_file.exists() and log_file.is_file():
            log_file.write_text("", encoding="utf-8")


def render_access_maps(state: dict, access_rules: list[dict]) -> list[str]:
    groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
    blocks = []
    for index, rule in enumerate(access_rules, start=1):
        condition_groups = rule.get("conditionGroups") if isinstance(rule.get("conditionGroups"), list) else []
        if condition_groups:
            for group_index, condition_group in enumerate(condition_groups, start=1):
                for condition_index, condition in enumerate(condition_group.get("conditions") or [], start=1):
                    items = collect_condition_ip_items(condition, groups)
                    if items:
                        blocks.append(render_geo_map(access_condition_geo_var(index, group_index, condition_index), items))
            continue

        items = collect_access_ips(rule, groups)
        if not items:
            continue
        blocks.append(render_geo_map(f"sfl_access_ip_{index}", items))
    return blocks


def render_bot_detection_maps() -> list[str]:
    return [
        "map $http_user_agent $sfl_bad_bot_ua {",
        "    default 0;",
        f"    ~*{BOT_BLOCK_UA_PATTERN} 1;",
        "}",
        "",
        "map $http_user_agent $sfl_suspicious_ua {",
        "    default 0;",
        f"    ~*{GOOD_BOT_UA_PATTERN} 0;",
        f"    ~*{BOT_CHALLENGE_UA_PATTERN} 1;",
        "}",
        "",
        "map $http_user_agent $sfl_missing_user_agent {",
        "    default 0;",
        "    '' 1;",
        "}",
        "",
        "map $http_accept $sfl_missing_accept {",
        "    default 0;",
        "    '' 1;",
        "}",
        "",
        "map $http_referer $sfl_bad_referer {",
        "    default 0;",
        f"    ~*{BOT_BLOCK_UA_PATTERN} 1;",
        "}",
        "",
        "map $request_method $sfl_unsafe_method {",
        "    default 0;",
        "    ~*^(?:TRACE|TRACK|CONNECT)$ 1;",
        "}",
        "",
    ]


def render_challenge_maps() -> list[str]:
    return [
        "map $cookie_freewaf_challenge $sfl_challenge_passed {",
        "    default 0;",
        "    passed 1;",
        "}",
        "",
    ]


def render_global_rate_limit_zones(rate_limit: dict) -> list[str]:
    rate = nginx_rate(rate_limit)
    return [
        f"limit_req_zone $binary_remote_addr zone=freewaf_rate:10m rate={rate};",
        f"limit_req_zone \"$remote_addr|$request_method|$http_user_agent\" zone=freewaf_rate_fingerprint:10m rate={rate};",
    ]


def render_bot_limit_zones(sites: list[dict]) -> list[str]:
    zones = []
    for site in sites:
        protection = site_bot_protection(site)
        if not protection.get("antiReplay"):
            continue
        zones.append(
            f"limit_req_zone \"$binary_remote_addr|$request_method|$request_uri|$http_user_agent\" zone={bot_replay_zone_name(site)}:10m rate=1r/s;"
        )
    return zones


def render_geo_map(variable_name: str, items: list[str]) -> str:
    lines = [
        f"geo ${variable_name} {{",
        "    default 0;",
    ]
    for item in items:
        lines.append(f"    {item} 1;")
    lines.append("}")
    return "\n".join(lines)


def site_hostnames(site: dict) -> list[str]:
    hostnames = site.get("hostnames") if isinstance(site.get("hostnames"), list) else []
    values = [str(hostname).strip() for hostname in hostnames if str(hostname or "").strip()]
    return values or ["_"]


def domain_config_filename(site: dict, hostname: str) -> str:
    site_id = safe_identifier(site.get("id") or site.get("name") or "site")
    domain_id = safe_identifier(str(hostname or "_").replace("*.", "wildcard_").replace("*", "catchall"))
    return f"{site_id}__{domain_id}.conf"


def render_site_server(site: dict, state: dict, certificates: dict[str, dict], hostname: str | None = None) -> str:
    hostnames = [hostname] if hostname else site_hostnames(site)
    render_site = {**site, "hostnames": hostnames}
    server_name = " ".join(escape_server_name(name) for name in hostnames)
    app_type = application_type(site)
    upstreams = site_upstreams(site)
    upstream_scheme = urlparse(upstreams[0]).scheme if upstreams else "http"
    upstream_name = backend_name(site, hostname)
    tls = site.get("tls") or {}
    certificate = certificates.get(tls.get("certificateId"))
    has_tls = bool(tls.get("enabled") and certificate)
    proxy = site_proxy(site)
    ports = site_ports(site)
    http_ports = [port for port, is_ssl in ports if not is_ssl]
    https_ports = [port for port, is_ssl in ports if is_ssl]
    blocks = [render_upstream(upstream_name, upstreams)] if app_type == "reverse_proxy" and upstreams else []

    redirect_code = int(proxy.get("redirectStatusCode") or site.get("redirectStatusCode") or 301)
    first_https_port = https_ports[0] if https_ports else int(site.get("listen") or 443)
    if has_tls and proxy.get("forceHttps") and redirect_code:
        for port in http_ports or [int(tls.get("httpListen") or 80)]:
            blocks.append(render_redirect_server(render_site, state, server_name, port, first_https_port, proxy, redirect_code))
    else:
        for port in http_ports:
            blocks.append(render_proxy_server(render_site, state, certificates, upstream_name, upstream_scheme, port, False, server_name, proxy))

    if https_ports:
        if has_tls:
            for port in https_ports:
                blocks.append(render_proxy_server(render_site, state, certificates, upstream_name, upstream_scheme, port, True, server_name, proxy))
        else:
            blocks.append(
                "\n".join(
                    [
                        f"# Site {nginx_comment(site.get('name'))} has HTTPS ports configured,",
                        "# but TLS is disabled or no valid certificate is selected.",
                    ]
                )
            )

    if not blocks:
        blocks.append(render_proxy_server(render_site, state, certificates, upstream_name, upstream_scheme, int(site.get("listen") or 8080), False, server_name, proxy))

    return "\n\n".join(blocks)


def render_upstream(name: str, upstreams: list[str]) -> str:
    lines = [f"upstream {name} {{"]
    for upstream in upstreams:
        parsed = urlparse(upstream)
        lines.append(f"    server {nginx_path(parsed.netloc)};")
    lines.extend(["    keepalive 128;", "    keepalive_timeout 75;", "}"])
    return "\n".join(lines)


def render_redirect_server(site: dict, state: dict, server_name: str, port: int, https_port: int, proxy: dict, redirect_code: int) -> str:
    listen_suffix = " default_server" if proxy.get("defaultServer") else ""
    lines = [
        "server {",
        f"    listen 0.0.0.0:{port}{listen_suffix};",
        *render_ipv6_listen(port, False, proxy),
        f"    server_name {server_name};",
        "",
        "    set $sfl_block 0;",
        "    set $sfl_allow 0;",
        "    set $sfl_challenge 0;",
        "    set $sfl_verdict allow;",
        "    set $sfl_reason \"Allowed\";",
        "",
        *render_log_directives(site, proxy),
        "    error_page 460 = @freewaf_block;",
        "    error_page 461 = @freewaf_challenge;",
        *render_rate_limit_error_page(site),
        "",
        *render_site_waf_directives(site, state),
        "",
        *render_safeline_locations(site),
        "",
        *render_internal_waf_locations(site),
        "",
        "    location / {",
        "        if ($sfl_block = 1) {",
        "            return 460;",
        "        }",
        "        if ($sfl_challenge = 1) {",
        "            return 461;",
        "        }",
        *render_rate_limit(state, site),
        *render_bot_replay_limit(site),
        f"        return {redirect_code} https://$host:{https_port}$request_uri;",
        "    }",
        "}",
    ]
    return "\n".join(lines)


def render_proxy_server(
    site: dict,
    state: dict,
    certificates: dict[str, dict],
    upstream_name: str,
    upstream_scheme: str,
    port: int,
    is_ssl: bool,
    server_name: str,
    proxy: dict,
) -> str:
    tls = site.get("tls") or {}
    certificate = certificates.get(tls.get("certificateId"))
    listen_flags = []
    if is_ssl:
        listen_flags.append("ssl")
        if proxy.get("http2"):
            listen_flags.append("http2")
    if proxy.get("defaultServer"):
        listen_flags.append("default_server")
    listen_suffix = f" {' '.join(listen_flags)}" if listen_flags else ""

    lines = [
        "server {",
        f"    listen 0.0.0.0:{port}{listen_suffix};",
        *render_ipv6_listen(port, is_ssl, proxy),
        f"    server_name {server_name};",
        "",
        "    set $sfl_block 0;",
        "    set $sfl_allow 0;",
        "    set $sfl_challenge 0;",
        "    set $sfl_verdict allow;",
        "    set $sfl_reason \"Allowed\";",
        "",
        *render_log_directives(site, proxy),
        "    error_page 460 = @freewaf_block;",
        "    error_page 461 = @freewaf_challenge;",
        *render_rate_limit_error_page(site),
        "    error_page 502 =502 /.safeline/bad_gateway_page;",
        "    error_page 504 =504 /.safeline/gateway_timeout_page;",
        "",
    ]
    if is_ssl and certificate:
        lines.extend(
            [
                f"    ssl_certificate {nginx_path(certificate['certFile'])};",
                f"    ssl_certificate_key {nginx_path(certificate['keyFile'])};",
                "    ssl_protocols TLSv1.2 TLSv1.3;",
                "    ssl_session_cache shared:SSL:10m;",
                "    error_page 497 =302 https://$host:$server_port$request_uri;",
                "",
            ]
        )

    if proxy.get("strictHost"):
        lines.extend(render_strict_host(site))

    lines.extend(render_compression_directives(proxy))

    auth_lines = render_auth_feature(site)
    if auth_lines:
        lines.extend(auth_lines)

    lines.extend(render_site_waf_directives(site, state))
    lines.extend(
        [
            "",
            *render_safeline_locations(site),
            "",
            *render_internal_waf_locations(site),
            "",
            "    location / {",
            "        if ($sfl_block = 1) {",
            "            return 460;",
            "        }",
            "        if ($sfl_challenge = 1) {",
            "            return 461;",
            "        }",
            *render_application_location(site, state, upstream_name, upstream_scheme, proxy, is_ssl),
            "    }",
            "}",
        ]
    )

    return "\n".join(lines)


def render_site_waf_directives(site: dict, state: dict) -> list[str]:
    rules = [
        rule
        for rule in state.get("rules", [])
        if rule.get("enabled")
        and rule.get("action") != "allow"
        and (rule.get("siteId") == "*" or rule.get("siteId") == site.get("id"))
        and should_emit_rule_for_site(rule, site)
    ]
    allow_rules = [
        rule
        for rule in state.get("rules", [])
        if rule.get("enabled")
        and rule.get("action") == "allow"
        and (rule.get("siteId") == "*" or rule.get("siteId") == site.get("id"))
    ]
    access_rules = [
        (index, rule)
        for index, rule in enumerate([rule for rule in state.get("accessRules", []) if rule.get("enabled")], start=1)
        if rule.get("siteId") in {"*", site.get("id")}
    ]

    lines = []
    rule_index = 0
    for access_index, access_rule in [item for item in access_rules if item[1].get("action") == "allow"]:
        rule_index += 1
        lines.extend(render_access_rule_if(access_rule, access_index, "allow", rule_index, state))

    for access_index, access_rule in [item for item in access_rules if item[1].get("action") != "allow"]:
        rule_index += 1
        effect = "monitor" if site.get("mode") == "monitor" or access_rule.get("action") == "monitor" else "block"
        lines.extend(render_access_rule_if(access_rule, access_index, effect, rule_index, state))

    for rule in allow_rules:
        rule_index += 1
        lines.extend(render_rule_if(rule, "allow", rule_index))

    for rule in rules:
        rule_index += 1
        if site.get("mode") == "monitor" or rule.get("action") == "monitor":
            lines.extend(render_rule_if(rule, "monitor", rule_index))
        else:
            lines.extend(render_rule_if(rule, "block", rule_index))

    lines.extend(render_bot_protection(site))
    lines.extend(render_acl_notes(site))
    return lines


def render_internal_waf_locations(site: dict) -> list[str]:
    return [
        "    location @freewaf_block {",
        "        internal;",
        "        add_header X-FreeWAF-Verdict block always;",
        "        default_type text/html;",
        f"        return 403 '{block_page(site)}';",
        "    }",
        "",
        "    location @freewaf_rate_limited {",
        "        internal;",
        "        set $sfl_verdict block;",
        "        set $sfl_reason \"HTTP flood rate limit\";",
        "        add_header X-FreeWAF-Verdict block always;",
        "        default_type text/html;",
        f"        return 429 '{rate_limit_page(site)}';",
        "    }",
        "",
        "    location @freewaf_challenge {",
        "        internal;",
        "        set $sfl_verdict challenge;",
        "        set $sfl_reason \"Browser challenge required\";",
        "        add_header X-FreeWAF-Verdict challenge always;",
        "        add_header Set-Cookie \"freewaf_challenge=passed; Max-Age=1800; Path=/; SameSite=Lax\" always;",
        "        add_header Cache-Control \"no-store\" always;",
        "        return 302 $request_uri;",
        "    }",
    ]


def application_type(site: dict) -> str:
    value = str(site.get("applicationType") or "reverse_proxy").lower().replace("-", "_")
    return value if value in {"reverse_proxy", "static_files", "redirect"} else "reverse_proxy"


def render_application_location(site: dict, state: dict, upstream_name: str, upstream_scheme: str, proxy: dict, is_ssl: bool) -> list[str]:
    app_type = application_type(site)
    if app_type == "redirect":
        redirect = site.get("redirect") if isinstance(site.get("redirect"), dict) else {}
        address = nginx_path(redirect.get("address") or "http://127.0.0.1")
        status = int(redirect.get("statusCode") or proxy.get("redirectStatusCode") or 301)
        return [
            *render_hsts_header(proxy, is_ssl),
            *render_dynamic_protection_headers(site),
            *render_bot_replay_limit(site),
            f"        return {status} {address}$request_uri;",
        ]

    if app_type == "static_files":
        root = static_root(site)
        return [
            *render_hsts_header(proxy, is_ssl),
            *render_dynamic_protection_headers(site),
            *render_bot_replay_limit(site),
            f"        root {nginx_path(root)};",
            "        try_files $uri $uri/ =404;",
        ]

    return [
        "        proxy_http_version 1.1;",
        "        proxy_set_header Upgrade $http_upgrade;",
        "        proxy_set_header Connection $sfl_connection_upgrade;",
        f"        proxy_set_header Host {proxy.get('hostHeader') or '$http_host'};",
        "        proxy_set_header X-Real-IP $remote_addr;",
        f"        proxy_set_header X-Forwarded-For {xff_value(proxy)};",
        f"        proxy_set_header X-Forwarded-Proto {proxy.get('xForwardedProto') or '$scheme'};",
        f"        proxy_set_header X-Forwarded-Host {proxy.get('xForwardedHost') or '$http_host'};",
        "        proxy_set_header X-FreeWAF $sfl_verdict;",
        *render_hsts_header(proxy, is_ssl),
        *render_dynamic_protection_headers(site),
        *render_proxy_ssl(upstream_scheme, proxy),
        *render_rate_limit(state, site),
        *render_bot_replay_limit(site),
        f"        proxy_pass {upstream_scheme}://{upstream_name};",
    ]


def static_root(site: dict) -> str:
    static = site.get("static") if isinstance(site.get("static"), dict) else {}
    if static.get("root"):
        return str(static["root"])
    base = os.environ.get("NGINX_STATIC_ROOT", "./public/static").replace("\\", "/").rstrip("/")
    return f"{base}/{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def site_upstreams(site: dict) -> list[str]:
    if application_type(site) != "reverse_proxy":
        return []
    upstreams = site.get("upstreams") if isinstance(site.get("upstreams"), list) else []
    values = [str(item) for item in upstreams if str(item or "").strip()]
    return values or [str(site.get("origin") or "http://127.0.0.1:9090")]


def backend_name(site: dict, hostname: str | None = None) -> str:
    suffix = f"_{safe_identifier(hostname)}" if hostname else ""
    return f"backend_{safe_identifier(site.get('id') or site.get('name') or 'site')}{suffix}"


def site_ports(site: dict) -> list[tuple[int, bool]]:
    raw_ports = site.get("ports") if isinstance(site.get("ports"), list) else []
    parsed = [parse_site_port(value) for value in raw_ports]
    parsed = [value for value in parsed if value]
    if parsed:
        return list(dict.fromkeys(parsed))
    tls = site.get("tls") or {}
    if tls.get("enabled"):
        if tls.get("redirectHttp"):
            return [(int(tls.get("httpListen") or 80), False), (int(site.get("listen") or 443), True)]
        return [(int(site.get("listen") or 443), True)]
    return [(int(site.get("listen") or 8080), False)]


def parse_site_port(value) -> tuple[int, bool] | None:
    item = str(value or "").strip().lower()
    if not item:
        return None
    is_ssl = item.endswith("_ssl")
    raw_port = item[:-4] if is_ssl else item
    if not re.match(r"^\d+$", raw_port):
        return None
    port = int(raw_port)
    if port < 1 or port > 65535:
        return None
    return port, is_ssl


def site_proxy(site: dict) -> dict:
    tls = site.get("tls") if isinstance(site.get("tls"), dict) else {}
    proxy = site.get("proxy") if isinstance(site.get("proxy"), dict) else {}
    return {
        "forceHttps": bool(proxy.get("forceHttps", tls.get("redirectHttp", False))),
        "redirectStatusCode": int(proxy.get("redirectStatusCode") or site.get("redirectStatusCode") or 301),
        "hsts": bool(proxy.get("hsts", bool(tls.get("enabled")))),
        "hstsMaxAge": str(proxy.get("hstsMaxAge") or "15768000"),
        "gzip": proxy.get("gzip") is not False,
        "brotli": bool(proxy.get("brotli")),
        "http2": proxy.get("http2") is not False and tls.get("http2", True) is not False,
        "ipv6": bool(proxy.get("ipv6")),
        "resetXff": proxy.get("resetXff") is not False,
        "defaultServer": bool(proxy.get("defaultServer")),
        "strictHost": bool(proxy.get("strictHost")),
        "accessLog": proxy.get("accessLog") is not False,
        "hostHeader": nginx_value(proxy.get("hostHeader") or "$http_host"),
        "xForwardedProto": nginx_value(proxy.get("xForwardedProto") or "$scheme"),
        "xForwardedHost": nginx_value(proxy.get("xForwardedHost") or "$http_host"),
        "proxySslServerName": proxy.get("proxySslServerName") is not False,
    }


def render_ipv6_listen(port: int, is_ssl: bool, proxy: dict) -> list[str]:
    if not proxy.get("ipv6"):
        return []
    flags = ["ssl"] if is_ssl else []
    if is_ssl and proxy.get("http2"):
        flags.append("http2")
    if proxy.get("defaultServer"):
        flags.append("default_server")
    suffix = f" {' '.join(flags)}" if flags else ""
    return [f"    listen [::]:{port}{suffix};"]


def render_log_directives(site: dict, proxy: dict) -> list[str]:
    lines = []
    if proxy.get("accessLog"):
        lines.append(f"    access_log {nginx_site_access_log_directive(site)} freewaf;")
    else:
        lines.append("    access_log off;")
    lines.append(f"    error_log {nginx_site_error_log_directive(site)};")
    return lines


def render_strict_host(site: dict) -> list[str]:
    regex = server_names_regex(site.get("hostnames") or [])
    if not regex:
        return []
    return [
        f"    if ($host !~* {nginx_regex(regex)}) {{",
        "        return 404;",
        "    }",
        "",
    ]


def server_names_regex(hostnames: list[str]) -> str:
    patterns = []
    for hostname in hostnames:
        item = str(hostname or "").strip().lower()
        if not item or item in {"*", "_"}:
            continue
        if item.startswith("*."):
            patterns.append(r"(?:.+\.)?" + re.escape(item[2:]))
        else:
            patterns.append(re.escape(item))
    return f"^(?:{'|'.join(patterns)})$" if patterns else ""


def render_compression_directives(proxy: dict) -> list[str]:
    lines = [f"    gzip {'on' if proxy.get('gzip') else 'off'};"]
    if proxy.get("brotli"):
        if os.environ.get("NGINX_HAS_BROTLI", "false").lower() == "true":
            lines.append("    brotli on;")
        else:
            lines.append("    # Brotli is enabled in this application; set NGINX_HAS_BROTLI=true to emit brotli on;")
    lines.append("")
    return lines


def render_acl_notes(site: dict) -> list[str]:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    if not acl.get("enabled"):
        return []
    notes = []
    attack = acl.get("attackLimit") if isinstance(acl.get("attackLimit"), dict) else {}
    error = acl.get("errorLimit") if isinstance(acl.get("errorLimit"), dict) else {}
    if attack.get("enabled"):
        notes.extend(
            [
                f"    # Basic Attack Limit: {int(attack.get('count') or 10)} attacks / {int(attack.get('period') or 60)}s -> {attack.get('action') or 'block'}.",
                "    # Native Nginx cannot count detector-classified attacks without a detector module.",
            ]
        )
    if error.get("enabled"):
        notes.extend(
            [
                f"    # Basic Error Limit: {int(error.get('count') or 10)} responses / {int(error.get('period') or 10)}s for status {', '.join(error.get('statusCodes') or ['403', '404'])}.",
                "    # SafeLine CE enforces this via management/detector state; FreeWAF records the policy for parity.",
            ]
        )
    return [*notes, ""] if notes else []


def render_safeline_locations(site: dict) -> list[str]:
    challenge_url = os.environ.get("NGINX_CHAOS_CHALLENGE_URL", "").strip()
    static_dir = os.environ.get("NGINX_FREEWAF_STATIC_DIR", "").strip()
    lines = [
        "    location = /.safeline/forbidden_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 403 '{block_page(site)}';",
        "    }",
        "    location = /.safeline/acl_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 429 '{error_page_html('Request limited', 'FreeWAF rate limit was triggered.')}';",
        "    }",
        "    location = /.safeline/bad_gateway_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 502 '{error_page_html('Bad gateway', 'The protected upstream did not return a valid response.')}';",
        "    }",
        "    location = /.safeline/gateway_timeout_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 504 '{error_page_html('Gateway timeout', 'The protected upstream timed out.')}';",
        "    }",
        "    location ^~ /.safeline/offline_page {",
        "        internal;",
        "        add_header cache-control no-cache;",
        "        default_type text/html;",
        f"        return 503 '{error_page_html('Application offline', 'This application is temporarily unavailable.')}';",
        "    }",
        "    location ^~ /.safeline/challenge/v2/ {",
    ]
    if challenge_url:
        lines.extend(
            [
                f"        proxy_pass {nginx_path(challenge_url)};",
                "        proxy_set_header Host $host;",
            ]
        )
    else:
        lines.append("        return 204;")
    lines.extend(["    }", "    location ^~ /.safeline/static {"])
    if static_dir:
        lines.extend(["        charset utf-8;", f"        alias {nginx_path(static_dir)};"])
    else:
        lines.append("        return 404;")
    lines.append("    }")
    return lines


def xff_value(proxy: dict) -> str:
    return "$remote_addr" if proxy.get("resetXff") else "$proxy_add_x_forwarded_for"


def render_hsts_header(proxy: dict, is_ssl: bool) -> list[str]:
    if not is_ssl or not proxy.get("hsts"):
        return []
    max_age = re.sub(r"[^0-9]", "", str(proxy.get("hstsMaxAge") or "15768000")) or "15768000"
    return [f"        add_header Strict-Transport-Security \"max-age={max_age};\" always;"]


def render_dynamic_protection_headers(site: dict) -> list[str]:
    dynamic = site_bot_protection(site).get("dynamicProtection") or {}
    if not dynamic.get("enabled"):
        return []
    enabled_parts = [
        name
        for name, enabled in (
            ("html", dynamic.get("html")),
            ("js", dynamic.get("js")),
            ("watermark", dynamic.get("watermark")),
        )
        if enabled
    ]
    value = ",".join(enabled_parts) or "on"
    return [
        f"        add_header X-FreeWAF-Dynamic-Protection \"{value}\" always;",
        "        add_header Cache-Control \"no-transform\" always;",
    ]


def render_bot_replay_limit(site: dict) -> list[str]:
    if not site_bot_protection(site).get("antiReplay"):
        return []
    return [f"        limit_req zone={bot_replay_zone_name(site)} burst=1 nodelay;"]


def render_proxy_ssl(upstream_scheme: str, proxy: dict) -> list[str]:
    if upstream_scheme != "https" or not proxy.get("proxySslServerName"):
        return []
    return [
        "        proxy_ssl_server_name on;",
        "        proxy_ssl_name $host;",
    ]


def render_acl_limit_zones(sites: list[dict]) -> list[str]:
    zones = []
    for site in sites:
        limit = active_acl_access_limit(site)
        if not limit:
            continue
        if acl_limit_action(limit) == "challenge_v1":
            zones.extend(
                [
                    f"map $cookie_freewaf_challenge ${acl_key_name(site)} {{",
                    "    default $binary_remote_addr;",
                    "    passed \"\";",
                    "}",
                    "",
                    f"map $cookie_freewaf_challenge ${acl_fingerprint_key_name(site)} {{",
                    "    default \"$remote_addr|$request_method|$http_user_agent\";",
                    "    passed \"\";",
                    "}",
                    "",
                ]
            )
        zones.append(
            f"limit_req_zone {acl_limit_key(site, limit)} zone={acl_zone_name(site)}:10m rate={nginx_acl_rate(limit)};"
        )
        if site_features(site).get("httpFlood"):
            zones.append(
                f"limit_req_zone {acl_fingerprint_limit_key(site, limit)} zone={acl_fingerprint_zone_name(site)}:10m rate={nginx_acl_rate(limit)};"
            )
    return zones


def active_acl_access_limit(site: dict) -> dict | None:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    limit = acl.get("accessLimit") if isinstance(acl.get("accessLimit"), dict) else {}
    if not acl.get("enabled") or not limit.get("enabled") or acl_rate_limit_mode(site) == "global":
        return None
    return limit


def acl_rate_limit_mode(site: dict) -> str:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    mode = str(acl.get("rateLimitMode") or "custom").lower()
    return mode if mode in {"global", "custom"} else "custom"


def acl_waiting_room(site: dict) -> bool:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    return bool(acl.get("waitingRoom"))


def acl_zone_name(site: dict) -> str:
    return f"sfl_acl_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def acl_fingerprint_zone_name(site: dict) -> str:
    return f"{acl_zone_name(site)}_fp"


def acl_key_name(site: dict) -> str:
    return f"sfl_acl_key_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def acl_fingerprint_key_name(site: dict) -> str:
    return f"{acl_key_name(site)}_fp"


def acl_limit_key(site: dict, limit: dict) -> str:
    if acl_limit_action(limit) == "challenge_v1":
        return f"${acl_key_name(site)}"
    return "$binary_remote_addr"


def acl_fingerprint_limit_key(site: dict, limit: dict) -> str:
    if acl_limit_action(limit) == "challenge_v1":
        return f"${acl_fingerprint_key_name(site)}"
    return "\"$remote_addr|$request_method|$http_user_agent\""


def acl_limit_action(limit: dict | None) -> str:
    action = str((limit or {}).get("action") or "block").lower()
    return action if action in {"allow", "block", "challenge_v1", "monitor"} else "block"


def any_uses_challenge(sites: list[dict]) -> bool:
    return any(site_bot_protection(site).get("antiBotChallenge") or acl_limit_action(active_acl_access_limit(site)) == "challenge_v1" for site in sites)


def nginx_acl_rate(limit: dict) -> str:
    count = max(1, int(limit.get("count") or 200))
    period = max(1, int(limit.get("period") or 10))
    per_minute = max(1, round(count * 60 / period))
    if per_minute < 60:
        return f"{per_minute}r/m"
    return f"{max(1, round(count / period))}r/s"


def site_features(site: dict) -> dict:
    features = site.get("features") if isinstance(site.get("features"), dict) else {}
    return {
        "httpFlood": features.get("httpFlood") is not False,
        "botProtection": features.get("botProtection") is not False,
        "auth": bool(features.get("auth")),
        "attacks": features.get("attacks") is not False,
    }


def site_bot_protection(site: dict) -> dict:
    features = site_features(site)
    source = site.get("botProtection") if isinstance(site.get("botProtection"), dict) else {}
    dynamic = source.get("dynamicProtection") if isinstance(source.get("dynamicProtection"), dict) else {}
    anti_replay = source.get("antiReplay") if isinstance(source.get("antiReplay"), dict) else {}
    enabled = features["botProtection"] and source.get("enabled") is not False
    dynamic_enabled = enabled and bool(dynamic.get("enabled"))
    return {
        "enabled": enabled,
        "antiBotChallenge": enabled and source.get("antiBotChallenge") is not False,
        "dynamicProtection": {
            "enabled": dynamic_enabled,
            "html": dynamic_enabled and bool(dynamic.get("html")),
            "js": dynamic_enabled and bool(dynamic.get("js")),
            "watermark": dynamic_enabled and bool(dynamic.get("watermark")),
        },
        "antiReplay": enabled and bool(anti_replay.get("enabled")),
    }


def bot_replay_zone_name(site: dict) -> str:
    return f"sfl_replay_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def should_emit_rule_for_site(rule: dict, site: dict) -> bool:
    features = site_features(site)
    if rule.get("id") in BOT_RULE_IDS:
        return features["botProtection"]
    return features["attacks"]


def render_auth_feature(site: dict) -> list[str]:
    if not site_features(site).get("auth"):
        return []
    auth_file = os.environ.get("NGINX_AUTH_FILE", "").strip()
    if auth_file:
        return [
            "    auth_basic \"FreeWAF\";",
            f"    auth_basic_user_file {nginx_path(auth_file)};",
            "",
        ]
    return [
        "    # Auth feature is enabled for this site.",
        "    # Set NGINX_AUTH_FILE to emit native auth_basic directives.",
        "",
    ]


def render_bot_protection(site: dict) -> list[str]:
    protection = site_bot_protection(site)
    if not protection.get("antiBotChallenge"):
        return []

    effect = "monitor" if site.get("mode") == "monitor" else "block"
    lines = [
        "    set $sfl_bot_block 0;",
        "    set $sfl_bot_challenge 0;",
        "    if ($sfl_bad_bot_ua = 1) {",
        "        set $sfl_bot_block 1;",
        "    }",
        "    if ($sfl_bad_referer = 1) {",
        "        set $sfl_bot_block 1;",
        "    }",
        "    if ($sfl_unsafe_method = 1) {",
        "        set $sfl_bot_block 1;",
        "    }",
        "    if ($sfl_suspicious_ua = 1) {",
        "        set $sfl_bot_challenge 1;",
        "    }",
        "    if ($sfl_missing_user_agent = 1) {",
        "        set $sfl_bot_challenge 1;",
        "    }",
        "    if ($sfl_missing_accept = 1) {",
        "        set $sfl_bot_challenge 1;",
        "    }",
        "    if ($sfl_challenge_passed = 1) {",
        "        set $sfl_bot_challenge 0;",
        "    }",
        "    if ($sfl_allow = 1) {",
        "        set $sfl_bot_block 0;",
        "        set $sfl_bot_challenge 0;",
        "    }",
        "    if ($sfl_block = 1) {",
        "        set $sfl_bot_block 0;",
        "        set $sfl_bot_challenge 0;",
        "    }",
    ]

    if effect == "monitor":
        lines.extend(
            [
                "    if ($sfl_bot_block = 1) {",
                "        set $sfl_verdict monitor;",
                "        set $sfl_reason \"Bot protection matched scanner headers\";",
                "    }",
                "    if ($sfl_bot_challenge = 1) {",
                "        set $sfl_verdict monitor;",
                "        set $sfl_reason \"Bot protection matched suspicious headers\";",
                "    }",
                "",
            ]
        )
        return lines

    lines.extend(
        [
            "    if ($sfl_bot_block = 1) {",
            "        set $sfl_block 1;",
            "        set $sfl_verdict block;",
            "        set $sfl_reason \"Bot protection matched scanner headers\";",
            "    }",
            "    if ($sfl_bot_challenge = 1) {",
            "        set $sfl_challenge 1;",
            "        set $sfl_verdict challenge;",
            "        set $sfl_reason \"Bot protection matched suspicious headers\";",
            "    }",
            "",
        ]
    )
    return lines


def render_access_rule_if(rule: dict, access_index: int, effect: str, rule_index: int, state: dict) -> list[str]:
    match_var = f"$sfl_rule_{rule_index}"
    reason = nginx_string(rule.get("name") or rule.get("id") or "Access rule matched")
    condition_groups = access_condition_groups(rule, access_index, state)

    if not condition_groups:
        return [
            f"    # Access rule {nginx_comment(rule.get('name'))} has no active Nginx-native conditions.",
            "",
        ]

    lines = [f"    set {match_var} 0;"]
    for group_index, conditions in enumerate(condition_groups, start=1):
        token_name = f"sfl_access_{rule_index}_{group_index}"
        token_var = f"${token_name}"
        group_var = f"$sfl_access_{rule_index}_group_{group_index}"
        expected = "1" * len(conditions)
        lines.extend(
            [
                f"    set {token_var} \"\";",
                f"    set {group_var} 0;",
            ]
        )
        for condition in conditions:
            lines.extend(
                [
                    f"    if ({condition}) {{",
                    f"        set {token_var} \"${{{token_name}}}1\";",
                    "    }",
                ]
            )
        lines.extend(
            [
                f"    if ({token_var} = \"{expected}\") {{",
                f"        set {group_var} 1;",
                "    }",
                f"    if ({group_var} = 1) {{",
                f"        set {match_var} 1;",
                "    }",
            ]
        )

    if effect == "allow":
        if rule.get("continueDetect"):
            lines.extend(
                [
                    f"    if ({match_var} = 1) {{",
                    "        set $sfl_verdict allow;",
                    f"        set $sfl_reason \"Allowed by {reason}\";",
                    "    }",
                ]
            )
            return lines

        lines.extend(
            [
                f"    if ({match_var} = 1) {{",
                "        set $sfl_allow 1;",
                "        set $sfl_block 0;",
                "        set $sfl_verdict allow;",
                f"        set $sfl_reason \"Allowed by {reason}\";",
                "    }",
            ]
        )
        return lines

    verdict = "monitor" if effect == "monitor" else "block"
    block_value = "0" if effect == "monitor" else "1"
    lines.extend(
        [
            "    if ($sfl_allow = 1) {",
            f"        set {match_var} 0;",
            "    }",
            f"    if ({match_var} = 1) {{",
            f"        set $sfl_block {block_value};",
            f"        set $sfl_verdict {verdict};",
            f"        set $sfl_reason \"{reason}\";",
            "    }",
        ]
    )
    return lines


def access_condition_groups(rule: dict, access_index: int, state: dict) -> list[list[str]]:
    condition_groups = rule.get("conditionGroups") if isinstance(rule.get("conditionGroups"), list) else []
    if condition_groups:
        groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
        rendered_groups = []
        for group_index, condition_group in enumerate(condition_groups, start=1):
            rendered_conditions = []
            for condition_index, condition in enumerate(condition_group.get("conditions") or [], start=1):
                rendered = access_condition_expression(condition, access_index, group_index, condition_index, groups)
                if rendered:
                    rendered_conditions.append(rendered)
            if rendered_conditions:
                rendered_groups.append(rendered_conditions)
        return rendered_groups

    legacy_conditions = legacy_access_conditions(rule, access_index, state)
    return [legacy_conditions] if legacy_conditions else []


def legacy_access_conditions(rule: dict, access_index: int, state: dict) -> list[str]:
    groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
    conditions = []
    if collect_access_ips(rule, groups):
        conditions.append(f"$sfl_access_ip_{access_index} = 1")
    if rule.get("methods"):
        conditions.append(f"$request_method ~* {nginx_regex(exact_any_regex(rule['methods']))}")
    if rule.get("uriPatterns"):
        conditions.append(f"$request_uri ~* {nginx_regex(any_regex(rule['uriPatterns']))}")
    if rule.get("hostPatterns"):
        conditions.append(f"$host ~* {nginx_regex(any_regex(rule['hostPatterns']))}")
    if rule.get("userAgentPatterns"):
        conditions.append(f"$http_user_agent ~* {nginx_regex(any_regex(rule['userAgentPatterns']))}")
    return conditions


def access_condition_expression(condition: dict, access_index: int, group_index: int, condition_index: int, groups: dict[str, dict]) -> str | None:
    target = str(condition.get("target") or "source_ip")
    operator = str(condition.get("operator") or "equals")
    content = str(condition.get("content") or "")

    if target == "source_ip":
        if operator in {"cidr", "not_cidr", "in_ip_group", "not_in_ip_group"}:
            items = collect_condition_ip_items(condition, groups)
            if not items:
                return None
            expected = "0" if operator in {"not_cidr", "not_in_ip_group"} else "1"
            return f"${access_condition_geo_var(access_index, group_index, condition_index)} = {expected}"
        regex = exact_regex(content)
        negate = "!" if operator == "not_equals" else ""
        return f"$remote_addr {negate}~* {nginx_regex(regex)}"

    variable = access_condition_variable(target)
    if not variable:
        return None

    if operator == "equals":
        return f"{variable} ~* {nginx_regex(exact_regex(content))}"
    if operator == "not_equals":
        return f"{variable} !~* {nginx_regex(exact_regex(content))}"
    if operator == "contains":
        return f"{variable} ~* {nginx_regex(re.escape(content))}"
    if operator == "not_contains":
        return f"{variable} !~* {nginx_regex(re.escape(content))}"
    if operator == "regex":
        return f"{variable} ~* {nginx_regex(content)}"
    if operator == "not_regex":
        return f"{variable} !~* {nginx_regex(content)}"
    return None


def access_condition_variable(target: str) -> str | None:
    if target == "source_ip":
        return "$remote_addr"
    if target == "uri":
        return "$request_uri"
    if target == "host":
        return "$host"
    if target == "user_agent":
        return "$http_user_agent"
    if target == "method":
        return "$request_method"
    return None


def access_condition_geo_var(access_index: int, group_index: int, condition_index: int) -> str:
    return f"sfl_access_ip_{access_index}_{group_index}_{condition_index}"


def collect_condition_ip_items(condition: dict, groups: dict[str, dict]) -> list[str]:
    target = str(condition.get("target") or "")
    operator = str(condition.get("operator") or "")
    content = str(condition.get("content") or "")
    if target != "source_ip":
        return []
    if operator in {"cidr", "not_cidr"}:
        return [content] if content else []
    if operator in {"in_ip_group", "not_in_ip_group"}:
        return ip_group_items(groups.get(content, {}))
    return []


def collect_access_ips(rule: dict, groups: dict[str, dict]) -> list[str]:
    items = list(rule.get("ips") or [])
    for group_id in rule.get("ipGroupIds") or []:
        items.extend(ip_group_items(groups.get(group_id, {})))
    return list(dict.fromkeys(items))


def ip_group_items(group: dict | None) -> list[str]:
    if not group:
        return []
    items = list(group.get("items") or [])
    item_file = str(group.get("itemsFile") or "").strip()
    if item_file:
        path = Path(item_file)
        if path.exists() and path.is_file():
            file_items = [line.strip() for line in path.read_text(encoding="utf-8", errors="replace").splitlines() if line.strip()]
            items.extend(file_items)
    return list(dict.fromkeys(items))


def render_rule_if(rule: dict, effect: str, index: int) -> list[str]:
    target = str(rule.get("target") or "all")
    if target == "body":
        return [
            f"    # Rule {nginx_comment(rule.get('name'))} targets request body.",
            "    # Native Nginx cannot inspect request bodies here; use ModSecurity, Lua, or njs for body rules.",
            "",
        ]

    variables = target_variables(target)
    pattern = nginx_regex(rule.get("pattern") or "")
    reason = nginx_string(rule.get("name") or rule.get("id") or "Rule matched")
    match_var = f"$sfl_rule_{index}"
    lines = [f"    set {match_var} 0;"]
    for variable in variables:
        lines.extend(
            [
                f"    if ({variable} ~* {pattern}) {{",
                f"        set {match_var} 1;",
                "    }",
            ]
        )

    if effect == "allow":
        lines.extend(
            [
                f"    if ({match_var} = 1) {{",
                "        set $sfl_allow 1;",
                "        set $sfl_block 0;",
                "        set $sfl_verdict allow;",
                f"        set $sfl_reason \"Allowed by {reason}\";",
                "    }",
            ]
        )
        return lines

    verdict = "monitor" if effect == "monitor" else "block"
    block_value = "0" if effect == "monitor" else "1"
    lines.extend(
        [
            "    if ($sfl_allow = 1) {",
            f"        set {match_var} 0;",
            "    }",
            f"    if ({match_var} = 1) {{",
            f"        set $sfl_block {block_value};",
            f"        set $sfl_verdict {verdict};",
            f"        set $sfl_reason \"{reason}\";",
            "    }",
        ]
    )
    return lines


def target_variables(target: str) -> list[str]:
    if target == "url":
        return ["$request_uri"]
    if target == "method":
        return ["$request_method"]
    if target == "ip":
        return ["$remote_addr"]
    if target == "headers":
        return ["$http_user_agent", "$http_referer", "$http_content_type"]
    return ["$request_method", "$request_uri", "$http_user_agent", "$http_referer", "$remote_addr"]


def render_rate_limit(state: dict, site: dict) -> list[str]:
    waiting_room = acl_waiting_room(site)
    acl_limit = active_acl_access_limit(site)
    if acl_limit:
        burst = max(1, int(acl_limit.get("count") or 200))
        lines = [render_limit_req_directive(acl_zone_name(site), burst, waiting_room)]
        if site_features(site).get("httpFlood"):
            lines.append(render_limit_req_directive(acl_fingerprint_zone_name(site), burst, waiting_room))
        if acl_limit_action(acl_limit) == "monitor":
            lines.append("        limit_req_dry_run on;")
        return lines

    rate_limit = state.get("settings", {}).get("rateLimit", {})
    if not rate_limit.get("enabled") or not site_features(site).get("httpFlood"):
        return []
    burst = max(1, int(rate_limit.get("max") or 120))
    return [
        render_limit_req_directive("freewaf_rate", burst, waiting_room),
        render_limit_req_directive("freewaf_rate_fingerprint", burst, waiting_room),
    ]


def render_limit_req_directive(zone: str, burst: int, waiting_room: bool) -> str:
    suffix = "" if waiting_room else " nodelay"
    return f"        limit_req zone={zone} burst={burst}{suffix};"


def render_rate_limit_error_page(site: dict) -> list[str]:
    acl_limit = active_acl_access_limit(site)
    if acl_limit_action(acl_limit) == "challenge_v1":
        return ["    error_page 429 = @freewaf_challenge;"]
    return ["    error_page 429 = @freewaf_rate_limited;"]


def nginx_rate(rate_limit: dict) -> str:
    maximum = max(1, int(rate_limit.get("max") or 120))
    window_ms = max(1000, int(rate_limit.get("windowMs") or 60000))
    per_minute = max(1, round(maximum * 60000 / window_ms))
    return f"{per_minute}r/m"


def escape_server_name(value: str) -> str:
    safe = str(value or "_").replace(";", "").replace("{", "").replace("}", "").strip()
    if safe == "*":
        return "_"
    return safe or "_"


def nginx_regex(value: str) -> str:
    escaped = str(value).replace("\n", " ").replace("\r", " ").replace('"', '\\"')
    return f'"{escaped}"'


def any_regex(values: list[str]) -> str:
    return "(?:" + "|".join(str(value).replace("\n", " ").replace("\r", " ") for value in values if str(value).strip()) + ")"


def exact_regex(value: str) -> str:
    return "^" + re.escape(str(value or "")) + "$"


def exact_any_regex(values: list[str]) -> str:
    escaped = [str(value).replace("\\", "\\\\").replace(".", "\\.") for value in values if str(value).strip()]
    return "^(?:" + "|".join(escaped) + ")$"


def nginx_path(value: str) -> str:
    return str(value).replace("\\", "/").replace(";", "").replace("{", "").replace("}", "")


def nginx_value(value: str) -> str:
    return str(value or "").replace("\x00", "").replace(";", "").replace("{", "").replace("}", "").replace("\n", " ")


def nginx_string(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"').replace(";", "")


def nginx_comment(value: str) -> str:
    return str(value or "").replace("\n", " ").replace("\r", " ")


def safe_identifier(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", str(value or "site"))
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe[:48] or "site"


def block_page(site: dict) -> str:
    title = "Request blocked"
    message = f"FreeWAF blocked this request for {site.get('name', 'this site')}."
    return error_page_html(title, message)


def rate_limit_page(site: dict) -> str:
    title = "Request limited"
    message = f"FreeWAF rate-limited this request for {site.get('name', 'this site')}."
    return error_page_html(title, message)


def error_page_html(title: str, message: str) -> str:
    html = (
        "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{title}</title>"
        "<style>body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:#f5f7f8;color:#17202a;display:grid;min-height:100vh;place-items:center}"
        "main{width:min(560px,calc(100vw - 32px));background:#fff;border:1px solid #d8e0ea;border-radius:8px;padding:28px}"
        "h1{margin:0 0 12px;font-size:24px}p{line-height:1.55;margin:0;color:#526071}</style></head>"
        f"<body><main><h1>{title}</h1><p>{message}</p></main></body></html>"
    )
    return html.replace("\\", "\\\\").replace("'", "\\'")


def parse_int(value) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None
