from __future__ import annotations

import os
import json
import re
import shlex
import subprocess
from pathlib import Path
from urllib.parse import urlparse


NATIVE_TARGETS = {"all", "url", "headers", "method", "ip"}
BOT_RULE_IDS = {"builtin-scanner-agent"}


def nginx_output_file(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_OUTPUT_FILE", "./nginx/generated/freewaf.conf"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_access_log_file(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_ACCESS_LOG", "./logs/freewaf_access.log"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_access_log_directive() -> str:
    configured = os.environ.get("NGINX_ACCESS_LOG", "./logs/freewaf_access.log")
    return configured.replace("\\", "/")


def nginx_site_log_dir(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_SITE_LOG_DIR", "./logs/freewaf"))
    return configured if configured.is_absolute() else root_dir / configured


def nginx_site_log_dir_directive() -> str:
    return os.environ.get("NGINX_SITE_LOG_DIR", "./logs/freewaf").replace("\\", "/").rstrip("/")


def nginx_site_access_log_directive(site: dict) -> str:
    return f"{nginx_site_log_dir_directive()}/accesslog_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def nginx_site_error_log_directive(site: dict) -> str:
    return f"{nginx_site_log_dir_directive()}/errorlog_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def generate_nginx_config(state: dict) -> str:
    enabled_sites = [site for site in state.get("sites", []) if site.get("enabled")]
    enabled_access_rules = [rule for rule in state.get("accessRules", []) if rule.get("enabled")]
    blocks = [
        "# Generated by FreeWAF. Do not edit by hand.",
        "# Include this file inside the nginx http {} context.",
        "",
        "log_format freewaf escape=json '{\"time\":\"$time_iso8601\",\"remote_addr\":\"$remote_addr\",\"host\":\"$host\",\"method\":\"$request_method\",\"uri\":\"$request_uri\",\"status\":$status,\"bytes\":$body_bytes_sent,\"request_time\":$request_time,\"upstream_status\":\"$upstream_status\",\"verdict\":\"$sfl_verdict\",\"reason\":\"$sfl_reason\"}';",
        "",
        "map $http_upgrade $sfl_connection_upgrade {",
        "    default upgrade;",
        "    '' close;",
        "}",
        "",
    ]

    rate_limit = state.get("settings", {}).get("rateLimit", {})
    uses_global_rate = any(
        site_features(site).get("httpFlood") and not active_acl_access_limit(site)
        for site in enabled_sites
    )
    if rate_limit.get("enabled") and uses_global_rate:
        blocks.extend(
            [
                f"limit_req_zone $binary_remote_addr zone=freewaf_rate:10m rate={nginx_rate(rate_limit)};",
            ]
        )

    acl_zones = render_acl_limit_zones(enabled_sites)
    if acl_zones:
        blocks.extend(acl_zones)

    if (rate_limit.get("enabled") and uses_global_rate) or acl_zones:
        blocks.extend(["limit_req_status 429;", ""])

    access_maps = render_access_maps(state, enabled_access_rules)
    if access_maps:
        blocks.extend(access_maps)
        blocks.append("")

    if not enabled_sites:
        blocks.append("# No enabled sites.")
        return "\n".join(blocks) + "\n"

    certificates = {certificate["id"]: certificate for certificate in state.get("certificates", [])}
    for site in enabled_sites:
        blocks.append(render_site_server(site, state, certificates))

    return "\n\n".join(blocks) + "\n"


def write_nginx_config(root_dir: Path, state: dict) -> Path:
    output_file = nginx_output_file(root_dir)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    nginx_site_log_dir(root_dir).mkdir(parents=True, exist_ok=True)
    output_file.write_text(generate_nginx_config(state), encoding="utf-8")
    return output_file


def run_nginx_command(command: str | None) -> dict:
    if not command:
        return {"configured": False, "ok": False, "stdout": "", "stderr": "No command configured"}

    completed = subprocess.run(
        shlex.split(command),
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    return {
        "configured": True,
        "ok": completed.returncode == 0,
        "returnCode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def nginx_runtime(root_dir: Path) -> dict:
    return {
        "outputFile": str(nginx_output_file(root_dir)),
        "accessLog": str(nginx_access_log_file(root_dir)),
        "siteLogDir": str(nginx_site_log_dir(root_dir)),
        "certDir": str(nginx_cert_dir(root_dir)),
        "testCommand": os.environ.get("NGINX_TEST_CMD", "nginx -t"),
        "reloadCommand": os.environ.get("NGINX_RELOAD_CMD", "nginx -s reload"),
    }


def nginx_cert_dir(root_dir: Path) -> Path:
    configured = Path(os.environ.get("NGINX_CERT_DIR", "./nginx/certs"))
    return configured if configured.is_absolute() else root_dir / configured


def parse_nginx_logs(root_dir: Path, limit: int = 500) -> list[dict]:
    log_files = [nginx_access_log_file(root_dir)]
    site_log_dir = nginx_site_log_dir(root_dir)
    if site_log_dir.exists():
        log_files.extend(sorted(site_log_dir.glob("accesslog_*")))

    entries = []
    for log_file in log_files:
        if not log_file.exists() or not log_file.is_file():
            continue
        lines = log_file.read_text(encoding="utf-8", errors="replace").splitlines()
        for index, line in enumerate(reversed(lines[-limit:])):
            try:
                raw = json.loads(line)
            except json.JSONDecodeError:
                continue

            verdict = str(raw.get("verdict") or "allow")
            status = parse_int(raw.get("status"))
            reason = str(raw.get("reason") or ("Blocked by Nginx WAF" if verdict == "block" else "Allowed"))
            entries.append(
                {
                    "id": f"nginx-{safe_identifier(log_file.name)}-{len(lines) - index}",
                    "at": str(raw.get("time") or ""),
                    "siteId": None,
                    "siteName": str(raw.get("host") or "Nginx"),
                    "host": str(raw.get("host") or ""),
                    "method": str(raw.get("method") or ""),
                    "path": str(raw.get("uri") or ""),
                    "ip": str(raw.get("remote_addr") or ""),
                    "verdict": verdict,
                    "statusCode": status,
                    "upstreamStatus": parse_int(raw.get("upstream_status")),
                    "durationMs": int(float(raw.get("request_time") or 0) * 1000),
                    "reason": reason,
                    "matchedRules": [{"name": reason, "severity": "medium", "action": verdict}] if verdict != "allow" else [],
                    "userAgent": "",
                    "requestSize": 0,
                }
            )

    return sorted(entries, key=lambda entry: entry.get("at") or "", reverse=True)[:limit]


def clear_nginx_logs(root_dir: Path) -> None:
    log_files = [nginx_access_log_file(root_dir)]
    site_log_dir = nginx_site_log_dir(root_dir)
    if site_log_dir.exists():
        log_files.extend(sorted(site_log_dir.glob("accesslog_*")))
    for log_file in log_files:
        if log_file.exists() and log_file.is_file():
            log_file.write_text("", encoding="utf-8")


def render_access_maps(state: dict, access_rules: list[dict]) -> list[str]:
    groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
    blocks = []
    for index, rule in enumerate(access_rules, start=1):
        condition_groups = rule.get("conditionGroups") if isinstance(rule.get("conditionGroups"), list) else []
        if condition_groups:
            for group_index, condition_group in enumerate(condition_groups, start=1):
                for condition_index, condition in enumerate(condition_group.get("conditions") or [], start=1):
                    items = collect_condition_ip_items(condition, groups)
                    if items:
                        blocks.append(render_geo_map(access_condition_geo_var(index, group_index, condition_index), items))
            continue

        items = collect_access_ips(rule, groups)
        if not items:
            continue
        blocks.append(render_geo_map(f"sfl_access_ip_{index}", items))
    return blocks


def render_geo_map(variable_name: str, items: list[str]) -> str:
    lines = [
        f"geo ${variable_name} {{",
        "    default 0;",
    ]
    for item in items:
        lines.append(f"    {item} 1;")
    lines.append("}")
    return "\n".join(lines)


def render_site_server(site: dict, state: dict, certificates: dict[str, dict]) -> str:
    server_name = " ".join(escape_server_name(name) for name in site.get("hostnames", ["_"]))
    app_type = application_type(site)
    upstreams = site_upstreams(site)
    upstream_scheme = urlparse(upstreams[0]).scheme if upstreams else "http"
    upstream_name = backend_name(site)
    tls = site.get("tls") or {}
    certificate = certificates.get(tls.get("certificateId"))
    has_tls = bool(tls.get("enabled") and certificate)
    proxy = site_proxy(site)
    ports = site_ports(site)
    http_ports = [port for port, is_ssl in ports if not is_ssl]
    https_ports = [port for port, is_ssl in ports if is_ssl]
    blocks = [render_upstream(upstream_name, upstreams)] if app_type == "reverse_proxy" and upstreams else []

    redirect_code = int(proxy.get("redirectStatusCode") or site.get("redirectStatusCode") or 301)
    first_https_port = https_ports[0] if https_ports else int(site.get("listen") or 443)
    if has_tls and proxy.get("forceHttps") and redirect_code:
        for port in http_ports or [int(tls.get("httpListen") or 80)]:
            blocks.append(render_redirect_server(site, server_name, port, first_https_port, proxy, redirect_code))
    else:
        for port in http_ports:
            blocks.append(render_proxy_server(site, state, certificates, upstream_name, upstream_scheme, port, False, server_name, proxy))

    if https_ports:
        if has_tls:
            for port in https_ports:
                blocks.append(render_proxy_server(site, state, certificates, upstream_name, upstream_scheme, port, True, server_name, proxy))
        else:
            blocks.append(
                "\n".join(
                    [
                        f"# Site {nginx_comment(site.get('name'))} has HTTPS ports configured,",
                        "# but TLS is disabled or no valid certificate is selected.",
                    ]
                )
            )

    if not blocks:
        blocks.append(render_proxy_server(site, state, certificates, upstream_name, upstream_scheme, int(site.get("listen") or 8080), False, server_name, proxy))

    return "\n\n".join(blocks)


def render_upstream(name: str, upstreams: list[str]) -> str:
    lines = [f"upstream {name} {{"]
    for upstream in upstreams:
        parsed = urlparse(upstream)
        lines.append(f"    server {nginx_path(parsed.netloc)};")
    lines.extend(["    keepalive 128;", "    keepalive_timeout 75;", "}"])
    return "\n".join(lines)


def render_redirect_server(site: dict, server_name: str, port: int, https_port: int, proxy: dict, redirect_code: int) -> str:
    listen_suffix = " default_server" if proxy.get("defaultServer") else ""
    lines = [
        "server {",
        f"    listen 0.0.0.0:{port}{listen_suffix};",
        *render_ipv6_listen(port, False, proxy),
        f"    server_name {server_name};",
        *render_log_directives(site, proxy),
        f"    return {redirect_code} https://$host:{https_port}$request_uri;",
        "}",
    ]
    return "\n".join(lines)


def render_proxy_server(
    site: dict,
    state: dict,
    certificates: dict[str, dict],
    upstream_name: str,
    upstream_scheme: str,
    port: int,
    is_ssl: bool,
    server_name: str,
    proxy: dict,
) -> str:
    tls = site.get("tls") or {}
    certificate = certificates.get(tls.get("certificateId"))
    listen_flags = []
    if is_ssl:
        listen_flags.append("ssl")
        if proxy.get("http2"):
            listen_flags.append("http2")
    if proxy.get("defaultServer"):
        listen_flags.append("default_server")
    listen_suffix = f" {' '.join(listen_flags)}" if listen_flags else ""

    rules = [
        rule
        for rule in state.get("rules", [])
        if rule.get("enabled")
        and rule.get("action") != "allow"
        and (rule.get("siteId") == "*" or rule.get("siteId") == site.get("id"))
        and should_emit_rule_for_site(rule, site)
    ]
    allow_rules = [
        rule
        for rule in state.get("rules", [])
        if rule.get("enabled")
        and rule.get("action") == "allow"
        and (rule.get("siteId") == "*" or rule.get("siteId") == site.get("id"))
    ]
    access_rules = [
        (index, rule)
        for index, rule in enumerate([rule for rule in state.get("accessRules", []) if rule.get("enabled")], start=1)
        if rule.get("siteId") in {"*", site.get("id")}
    ]

    lines = [
        "server {",
        f"    listen 0.0.0.0:{port}{listen_suffix};",
        *render_ipv6_listen(port, is_ssl, proxy),
        f"    server_name {server_name};",
        "",
        "    set $sfl_block 0;",
        "    set $sfl_allow 0;",
        "    set $sfl_verdict allow;",
        "    set $sfl_reason \"Allowed\";",
        "",
        *render_log_directives(site, proxy),
        "    error_page 460 = @freewaf_block;",
        "    error_page 429 = /.safeline/acl_page;",
        "    error_page 502 =502 /.safeline/bad_gateway_page;",
        "    error_page 504 =504 /.safeline/gateway_timeout_page;",
        "",
    ]
    if is_ssl and certificate:
        lines.extend(
            [
                f"    ssl_certificate {nginx_path(certificate['certFile'])};",
                f"    ssl_certificate_key {nginx_path(certificate['keyFile'])};",
                "    ssl_protocols TLSv1.2 TLSv1.3;",
                "    ssl_session_cache shared:SSL:10m;",
                "    error_page 497 =302 https://$host:$server_port$request_uri;",
                "",
            ]
        )

    if proxy.get("strictHost"):
        lines.extend(render_strict_host(site))

    lines.extend(render_compression_directives(proxy))

    auth_lines = render_auth_feature(site)
    if auth_lines:
        lines.extend(auth_lines)

    rule_index = 0
    for access_index, access_rule in [item for item in access_rules if item[1].get("action") == "allow"]:
        rule_index += 1
        lines.extend(render_access_rule_if(access_rule, access_index, "allow", rule_index, state))

    for access_index, access_rule in [item for item in access_rules if item[1].get("action") != "allow"]:
        rule_index += 1
        effect = "monitor" if site.get("mode") == "monitor" or access_rule.get("action") == "monitor" else "block"
        lines.extend(render_access_rule_if(access_rule, access_index, effect, rule_index, state))

    for rule in allow_rules:
        rule_index += 1
        lines.extend(render_rule_if(rule, "allow", rule_index))

    for rule in rules:
        rule_index += 1
        if site.get("mode") == "monitor" or rule.get("action") == "monitor":
            lines.extend(render_rule_if(rule, "monitor", rule_index))
        else:
            lines.extend(render_rule_if(rule, "block", rule_index))

    lines.extend(render_acl_notes(site))
    lines.extend(
        [
            "",
            *render_safeline_locations(site),
            "",
            "    location @freewaf_block {",
            "        internal;",
            "        add_header X-FreeWAF-Verdict block always;",
            "        default_type text/html;",
            f"        return 403 '{block_page(site)}';",
            "    }",
            "",
            "    location / {",
            "        if ($sfl_block = 1) {",
            "            return 460;",
            "        }",
            *render_application_location(site, state, upstream_name, upstream_scheme, proxy, is_ssl),
            "    }",
            "}",
        ]
    )

    return "\n".join(lines)


def application_type(site: dict) -> str:
    value = str(site.get("applicationType") or "reverse_proxy").lower().replace("-", "_")
    return value if value in {"reverse_proxy", "static_files", "redirect"} else "reverse_proxy"


def render_application_location(site: dict, state: dict, upstream_name: str, upstream_scheme: str, proxy: dict, is_ssl: bool) -> list[str]:
    app_type = application_type(site)
    if app_type == "redirect":
        redirect = site.get("redirect") if isinstance(site.get("redirect"), dict) else {}
        address = nginx_path(redirect.get("address") or "http://127.0.0.1")
        status = int(redirect.get("statusCode") or proxy.get("redirectStatusCode") or 301)
        return [
            *render_hsts_header(proxy, is_ssl),
            f"        return {status} {address}$request_uri;",
        ]

    if app_type == "static_files":
        root = static_root(site)
        return [
            *render_hsts_header(proxy, is_ssl),
            f"        root {nginx_path(root)};",
            "        try_files $uri $uri/ =404;",
        ]

    return [
        "        proxy_http_version 1.1;",
        "        proxy_set_header Upgrade $http_upgrade;",
        "        proxy_set_header Connection $sfl_connection_upgrade;",
        f"        proxy_set_header Host {proxy.get('hostHeader') or '$http_host'};",
        "        proxy_set_header X-Real-IP $remote_addr;",
        f"        proxy_set_header X-Forwarded-For {xff_value(proxy)};",
        f"        proxy_set_header X-Forwarded-Proto {proxy.get('xForwardedProto') or '$scheme'};",
        f"        proxy_set_header X-Forwarded-Host {proxy.get('xForwardedHost') or '$http_host'};",
        "        proxy_set_header X-FreeWAF $sfl_verdict;",
        *render_hsts_header(proxy, is_ssl),
        *render_proxy_ssl(upstream_scheme, proxy),
        *render_rate_limit(state, site),
        f"        proxy_pass {upstream_scheme}://{upstream_name};",
    ]


def static_root(site: dict) -> str:
    static = site.get("static") if isinstance(site.get("static"), dict) else {}
    if static.get("root"):
        return str(static["root"])
    base = os.environ.get("NGINX_STATIC_ROOT", "./public/static").replace("\\", "/").rstrip("/")
    return f"{base}/{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def site_upstreams(site: dict) -> list[str]:
    if application_type(site) != "reverse_proxy":
        return []
    upstreams = site.get("upstreams") if isinstance(site.get("upstreams"), list) else []
    values = [str(item) for item in upstreams if str(item or "").strip()]
    return values or [str(site.get("origin") or "http://127.0.0.1:9090")]


def backend_name(site: dict) -> str:
    return f"backend_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def site_ports(site: dict) -> list[tuple[int, bool]]:
    raw_ports = site.get("ports") if isinstance(site.get("ports"), list) else []
    parsed = [parse_site_port(value) for value in raw_ports]
    parsed = [value for value in parsed if value]
    if parsed:
        return list(dict.fromkeys(parsed))
    tls = site.get("tls") or {}
    if tls.get("enabled"):
        if tls.get("redirectHttp"):
            return [(int(tls.get("httpListen") or 80), False), (int(site.get("listen") or 443), True)]
        return [(int(site.get("listen") or 443), True)]
    return [(int(site.get("listen") or 8080), False)]


def parse_site_port(value) -> tuple[int, bool] | None:
    item = str(value or "").strip().lower()
    if not item:
        return None
    is_ssl = item.endswith("_ssl")
    raw_port = item[:-4] if is_ssl else item
    if not re.match(r"^\d+$", raw_port):
        return None
    port = int(raw_port)
    if port < 1 or port > 65535:
        return None
    return port, is_ssl


def site_proxy(site: dict) -> dict:
    tls = site.get("tls") if isinstance(site.get("tls"), dict) else {}
    proxy = site.get("proxy") if isinstance(site.get("proxy"), dict) else {}
    return {
        "forceHttps": bool(proxy.get("forceHttps", tls.get("redirectHttp", False))),
        "redirectStatusCode": int(proxy.get("redirectStatusCode") or site.get("redirectStatusCode") or 301),
        "hsts": bool(proxy.get("hsts", bool(tls.get("enabled")))),
        "hstsMaxAge": str(proxy.get("hstsMaxAge") or "15768000"),
        "gzip": proxy.get("gzip") is not False,
        "brotli": bool(proxy.get("brotli")),
        "http2": proxy.get("http2") is not False and tls.get("http2", True) is not False,
        "ipv6": bool(proxy.get("ipv6")),
        "resetXff": proxy.get("resetXff") is not False,
        "defaultServer": bool(proxy.get("defaultServer")),
        "strictHost": bool(proxy.get("strictHost")),
        "accessLog": proxy.get("accessLog") is not False,
        "hostHeader": nginx_value(proxy.get("hostHeader") or "$http_host"),
        "xForwardedProto": nginx_value(proxy.get("xForwardedProto") or "$scheme"),
        "xForwardedHost": nginx_value(proxy.get("xForwardedHost") or "$http_host"),
        "proxySslServerName": proxy.get("proxySslServerName") is not False,
    }


def render_ipv6_listen(port: int, is_ssl: bool, proxy: dict) -> list[str]:
    if not proxy.get("ipv6"):
        return []
    flags = ["ssl"] if is_ssl else []
    if is_ssl and proxy.get("http2"):
        flags.append("http2")
    if proxy.get("defaultServer"):
        flags.append("default_server")
    suffix = f" {' '.join(flags)}" if flags else ""
    return [f"    listen [::]:{port}{suffix};"]


def render_log_directives(site: dict, proxy: dict) -> list[str]:
    lines = []
    if proxy.get("accessLog"):
        lines.append(f"    access_log {nginx_site_access_log_directive(site)} freewaf;")
    else:
        lines.append("    access_log off;")
    lines.append(f"    error_log {nginx_site_error_log_directive(site)};")
    return lines


def render_strict_host(site: dict) -> list[str]:
    regex = server_names_regex(site.get("hostnames") or [])
    if not regex:
        return []
    return [
        f"    if ($host !~* {nginx_regex(regex)}) {{",
        "        return 404;",
        "    }",
        "",
    ]


def server_names_regex(hostnames: list[str]) -> str:
    patterns = []
    for hostname in hostnames:
        item = str(hostname or "").strip().lower()
        if not item or item in {"*", "_"}:
            continue
        if item.startswith("*."):
            patterns.append(r"(?:.+\.)?" + re.escape(item[2:]))
        else:
            patterns.append(re.escape(item))
    return f"^(?:{'|'.join(patterns)})$" if patterns else ""


def render_compression_directives(proxy: dict) -> list[str]:
    lines = [f"    gzip {'on' if proxy.get('gzip') else 'off'};"]
    if proxy.get("brotli"):
        if os.environ.get("NGINX_HAS_BROTLI", "false").lower() == "true":
            lines.append("    brotli on;")
        else:
            lines.append("    # Brotli is enabled in this application; set NGINX_HAS_BROTLI=true to emit brotli on;")
    lines.append("")
    return lines


def render_acl_notes(site: dict) -> list[str]:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    if not acl.get("enabled"):
        return []
    notes = []
    attack = acl.get("attackLimit") if isinstance(acl.get("attackLimit"), dict) else {}
    error = acl.get("errorLimit") if isinstance(acl.get("errorLimit"), dict) else {}
    if attack.get("enabled"):
        notes.extend(
            [
                f"    # Basic Attack Limit: {int(attack.get('count') or 10)} attacks / {int(attack.get('period') or 60)}s -> {attack.get('action') or 'block'}.",
                "    # Native Nginx cannot count detector-classified attacks without a detector module.",
            ]
        )
    if error.get("enabled"):
        notes.extend(
            [
                f"    # Basic Error Limit: {int(error.get('count') or 10)} responses / {int(error.get('period') or 10)}s for status {', '.join(error.get('statusCodes') or ['403', '404'])}.",
                "    # SafeLine CE enforces this via management/detector state; FreeWAF records the policy for parity.",
            ]
        )
    return [*notes, ""] if notes else []


def render_safeline_locations(site: dict) -> list[str]:
    challenge_url = os.environ.get("NGINX_CHAOS_CHALLENGE_URL", "").strip()
    static_dir = os.environ.get("NGINX_FREEWAF_STATIC_DIR", "").strip()
    lines = [
        "    location = /.safeline/forbidden_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 403 '{block_page(site)}';",
        "    }",
        "    location = /.safeline/acl_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 429 '{error_page_html('Request limited', 'FreeWAF rate limit was triggered.')}';",
        "    }",
        "    location = /.safeline/bad_gateway_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 502 '{error_page_html('Bad gateway', 'The protected upstream did not return a valid response.')}';",
        "    }",
        "    location = /.safeline/gateway_timeout_page {",
        "        internal;",
        "        default_type text/html;",
        f"        return 504 '{error_page_html('Gateway timeout', 'The protected upstream timed out.')}';",
        "    }",
        "    location ^~ /.safeline/offline_page {",
        "        internal;",
        "        add_header cache-control no-cache;",
        "        default_type text/html;",
        f"        return 503 '{error_page_html('Application offline', 'This application is temporarily unavailable.')}';",
        "    }",
        "    location ^~ /.safeline/challenge/v2/ {",
    ]
    if challenge_url:
        lines.extend(
            [
                f"        proxy_pass {nginx_path(challenge_url)};",
                "        proxy_set_header Host $host;",
            ]
        )
    else:
        lines.append("        return 204;")
    lines.extend(["    }", "    location ^~ /.safeline/static {"])
    if static_dir:
        lines.extend(["        charset utf-8;", f"        alias {nginx_path(static_dir)};"])
    else:
        lines.append("        return 404;")
    lines.append("    }")
    return lines


def xff_value(proxy: dict) -> str:
    return "$remote_addr" if proxy.get("resetXff") else "$proxy_add_x_forwarded_for"


def render_hsts_header(proxy: dict, is_ssl: bool) -> list[str]:
    if not is_ssl or not proxy.get("hsts"):
        return []
    max_age = re.sub(r"[^0-9]", "", str(proxy.get("hstsMaxAge") or "15768000")) or "15768000"
    return [f"        add_header Strict-Transport-Security \"max-age={max_age};\" always;"]


def render_proxy_ssl(upstream_scheme: str, proxy: dict) -> list[str]:
    if upstream_scheme != "https" or not proxy.get("proxySslServerName"):
        return []
    return [
        "        proxy_ssl_server_name on;",
        "        proxy_ssl_name $host;",
    ]


def render_acl_limit_zones(sites: list[dict]) -> list[str]:
    zones = []
    for site in sites:
        limit = active_acl_access_limit(site)
        if not limit:
            continue
        zones.append(
            f"limit_req_zone $binary_remote_addr zone={acl_zone_name(site)}:10m rate={nginx_acl_rate(limit)};"
        )
    return zones


def active_acl_access_limit(site: dict) -> dict | None:
    acl = site.get("acl") if isinstance(site.get("acl"), dict) else {}
    limit = acl.get("accessLimit") if isinstance(acl.get("accessLimit"), dict) else {}
    if not acl.get("enabled") or not limit.get("enabled"):
        return None
    return limit


def acl_zone_name(site: dict) -> str:
    return f"sfl_acl_{safe_identifier(site.get('id') or site.get('name') or 'site')}"


def nginx_acl_rate(limit: dict) -> str:
    count = max(1, int(limit.get("count") or 200))
    period = max(1, int(limit.get("period") or 10))
    per_minute = max(1, round(count * 60 / period))
    if per_minute < 60:
        return f"{per_minute}r/m"
    return f"{max(1, round(count / period))}r/s"


def site_features(site: dict) -> dict:
    features = site.get("features") if isinstance(site.get("features"), dict) else {}
    return {
        "httpFlood": features.get("httpFlood") is not False,
        "botProtection": features.get("botProtection") is not False,
        "auth": bool(features.get("auth")),
        "attacks": features.get("attacks") is not False,
    }


def should_emit_rule_for_site(rule: dict, site: dict) -> bool:
    features = site_features(site)
    if rule.get("id") in BOT_RULE_IDS:
        return features["botProtection"]
    return features["attacks"]


def render_auth_feature(site: dict) -> list[str]:
    if not site_features(site).get("auth"):
        return []
    auth_file = os.environ.get("NGINX_AUTH_FILE", "").strip()
    if auth_file:
        return [
            "    auth_basic \"FreeWAF\";",
            f"    auth_basic_user_file {nginx_path(auth_file)};",
            "",
        ]
    return [
        "    # Auth feature is enabled for this site.",
        "    # Set NGINX_AUTH_FILE to emit native auth_basic directives.",
        "",
    ]


def render_access_rule_if(rule: dict, access_index: int, effect: str, rule_index: int, state: dict) -> list[str]:
    match_var = f"$sfl_rule_{rule_index}"
    reason = nginx_string(rule.get("name") or rule.get("id") or "Access rule matched")
    condition_groups = access_condition_groups(rule, access_index, state)

    if not condition_groups:
        return [
            f"    # Access rule {nginx_comment(rule.get('name'))} has no active Nginx-native conditions.",
            "",
        ]

    lines = [f"    set {match_var} 0;"]
    for group_index, conditions in enumerate(condition_groups, start=1):
        token_name = f"sfl_access_{rule_index}_{group_index}"
        token_var = f"${token_name}"
        group_var = f"$sfl_access_{rule_index}_group_{group_index}"
        expected = "1" * len(conditions)
        lines.extend(
            [
                f"    set {token_var} \"\";",
                f"    set {group_var} 0;",
            ]
        )
        for condition in conditions:
            lines.extend(
                [
                    f"    if ({condition}) {{",
                    f"        set {token_var} \"${{{token_name}}}1\";",
                    "    }",
                ]
            )
        lines.extend(
            [
                f"    if ({token_var} = \"{expected}\") {{",
                f"        set {group_var} 1;",
                "    }",
                f"    if ({group_var} = 1) {{",
                f"        set {match_var} 1;",
                "    }",
            ]
        )

    if effect == "allow":
        if rule.get("continueDetect"):
            lines.extend(
                [
                    f"    if ({match_var} = 1) {{",
                    "        set $sfl_verdict allow;",
                    f"        set $sfl_reason \"Allowed by {reason}\";",
                    "    }",
                ]
            )
            return lines

        lines.extend(
            [
                f"    if ({match_var} = 1) {{",
                "        set $sfl_allow 1;",
                "        set $sfl_block 0;",
                "        set $sfl_verdict allow;",
                f"        set $sfl_reason \"Allowed by {reason}\";",
                "    }",
            ]
        )
        return lines

    verdict = "monitor" if effect == "monitor" else "block"
    block_value = "0" if effect == "monitor" else "1"
    lines.extend(
        [
            "    if ($sfl_allow = 1) {",
            f"        set {match_var} 0;",
            "    }",
            f"    if ({match_var} = 1) {{",
            f"        set $sfl_block {block_value};",
            f"        set $sfl_verdict {verdict};",
            f"        set $sfl_reason \"{reason}\";",
            "    }",
        ]
    )
    return lines


def access_condition_groups(rule: dict, access_index: int, state: dict) -> list[list[str]]:
    condition_groups = rule.get("conditionGroups") if isinstance(rule.get("conditionGroups"), list) else []
    if condition_groups:
        groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
        rendered_groups = []
        for group_index, condition_group in enumerate(condition_groups, start=1):
            rendered_conditions = []
            for condition_index, condition in enumerate(condition_group.get("conditions") or [], start=1):
                rendered = access_condition_expression(condition, access_index, group_index, condition_index, groups)
                if rendered:
                    rendered_conditions.append(rendered)
            if rendered_conditions:
                rendered_groups.append(rendered_conditions)
        return rendered_groups

    legacy_conditions = legacy_access_conditions(rule, access_index, state)
    return [legacy_conditions] if legacy_conditions else []


def legacy_access_conditions(rule: dict, access_index: int, state: dict) -> list[str]:
    groups = {group["id"]: group for group in state.get("ipGroups", []) if group.get("enabled")}
    conditions = []
    if collect_access_ips(rule, groups):
        conditions.append(f"$sfl_access_ip_{access_index} = 1")
    if rule.get("methods"):
        conditions.append(f"$request_method ~* {nginx_regex(exact_any_regex(rule['methods']))}")
    if rule.get("uriPatterns"):
        conditions.append(f"$request_uri ~* {nginx_regex(any_regex(rule['uriPatterns']))}")
    if rule.get("hostPatterns"):
        conditions.append(f"$host ~* {nginx_regex(any_regex(rule['hostPatterns']))}")
    if rule.get("userAgentPatterns"):
        conditions.append(f"$http_user_agent ~* {nginx_regex(any_regex(rule['userAgentPatterns']))}")
    return conditions


def access_condition_expression(condition: dict, access_index: int, group_index: int, condition_index: int, groups: dict[str, dict]) -> str | None:
    target = str(condition.get("target") or "source_ip")
    operator = str(condition.get("operator") or "equals")
    content = str(condition.get("content") or "")

    if target == "source_ip":
        if operator in {"cidr", "not_cidr", "in_ip_group", "not_in_ip_group"}:
            items = collect_condition_ip_items(condition, groups)
            if not items:
                return None
            expected = "0" if operator in {"not_cidr", "not_in_ip_group"} else "1"
            return f"${access_condition_geo_var(access_index, group_index, condition_index)} = {expected}"
        regex = exact_regex(content)
        negate = "!" if operator == "not_equals" else ""
        return f"$remote_addr {negate}~* {nginx_regex(regex)}"

    variable = access_condition_variable(target)
    if not variable:
        return None

    if operator == "equals":
        return f"{variable} ~* {nginx_regex(exact_regex(content))}"
    if operator == "not_equals":
        return f"{variable} !~* {nginx_regex(exact_regex(content))}"
    if operator == "contains":
        return f"{variable} ~* {nginx_regex(re.escape(content))}"
    if operator == "not_contains":
        return f"{variable} !~* {nginx_regex(re.escape(content))}"
    if operator == "regex":
        return f"{variable} ~* {nginx_regex(content)}"
    if operator == "not_regex":
        return f"{variable} !~* {nginx_regex(content)}"
    return None


def access_condition_variable(target: str) -> str | None:
    if target == "source_ip":
        return "$remote_addr"
    if target == "uri":
        return "$request_uri"
    if target == "host":
        return "$host"
    if target == "user_agent":
        return "$http_user_agent"
    if target == "method":
        return "$request_method"
    return None


def access_condition_geo_var(access_index: int, group_index: int, condition_index: int) -> str:
    return f"sfl_access_ip_{access_index}_{group_index}_{condition_index}"


def collect_condition_ip_items(condition: dict, groups: dict[str, dict]) -> list[str]:
    target = str(condition.get("target") or "")
    operator = str(condition.get("operator") or "")
    content = str(condition.get("content") or "")
    if target != "source_ip":
        return []
    if operator in {"cidr", "not_cidr"}:
        return [content] if content else []
    if operator in {"in_ip_group", "not_in_ip_group"}:
        return list(groups.get(content, {}).get("items") or [])
    return []


def collect_access_ips(rule: dict, groups: dict[str, dict]) -> list[str]:
    items = list(rule.get("ips") or [])
    for group_id in rule.get("ipGroupIds") or []:
        items.extend(groups.get(group_id, {}).get("items") or [])
    return list(dict.fromkeys(items))


def render_rule_if(rule: dict, effect: str, index: int) -> list[str]:
    target = str(rule.get("target") or "all")
    if target == "body":
        return [
            f"    # Rule {nginx_comment(rule.get('name'))} targets request body.",
            "    # Native Nginx cannot inspect request bodies here; use ModSecurity, Lua, or njs for body rules.",
            "",
        ]

    variable = target_variable(target)
    pattern = nginx_regex(rule.get("pattern") or "")
    reason = nginx_string(rule.get("name") or rule.get("id") or "Rule matched")

    if effect == "allow":
        return [
            f"    if ({variable} ~* {pattern}) {{",
            "        set $sfl_allow 1;",
            "        set $sfl_block 0;",
            "        set $sfl_verdict allow;",
            f"        set $sfl_reason \"Allowed by {reason}\";",
            "    }",
        ]

    verdict = "monitor" if effect == "monitor" else "block"
    block_value = "0" if effect == "monitor" else "1"
    match_var = f"$sfl_rule_{index}"
    return [
        f"    set {match_var} 0;",
        f"    if ({variable} ~* {pattern}) {{",
        f"        set {match_var} 1;",
        "    }",
        "    if ($sfl_allow = 1) {",
        f"        set {match_var} 0;",
        "    }",
        f"    if ({match_var} = 1) {{",
        f"        set $sfl_block {block_value};",
        f"        set $sfl_verdict {verdict};",
        f"        set $sfl_reason \"{reason}\";",
        "    }",
    ]


def target_variable(target: str) -> str:
    if target == "url":
        return "$request_uri"
    if target == "method":
        return "$request_method"
    if target == "ip":
        return "$remote_addr"
    if target == "headers":
        return "$http_user_agent$http_referer$http_content_type"
    return "$request_method$request_uri$http_user_agent$http_referer$remote_addr"


def render_rate_limit(state: dict, site: dict) -> list[str]:
    acl_limit = active_acl_access_limit(site)
    if acl_limit:
        burst = max(1, int(acl_limit.get("count") or 200))
        return [f"        limit_req zone={acl_zone_name(site)} burst={burst} nodelay;"]

    rate_limit = state.get("settings", {}).get("rateLimit", {})
    if not rate_limit.get("enabled") or not site_features(site).get("httpFlood"):
        return []
    burst = max(1, int(rate_limit.get("max") or 120))
    return [f"        limit_req zone=freewaf_rate burst={burst} nodelay;"]


def nginx_rate(rate_limit: dict) -> str:
    maximum = max(1, int(rate_limit.get("max") or 120))
    window_ms = max(1000, int(rate_limit.get("windowMs") or 60000))
    per_minute = max(1, round(maximum * 60000 / window_ms))
    return f"{per_minute}r/m"


def escape_server_name(value: str) -> str:
    safe = str(value or "_").replace(";", "").replace("{", "").replace("}", "").strip()
    return safe or "_"


def nginx_regex(value: str) -> str:
    escaped = str(value).replace("\n", " ").replace("\r", " ").replace('"', '\\"')
    return f'"{escaped}"'


def any_regex(values: list[str]) -> str:
    return "(?:" + "|".join(str(value).replace("\n", " ").replace("\r", " ") for value in values if str(value).strip()) + ")"


def exact_regex(value: str) -> str:
    return "^" + re.escape(str(value or "")) + "$"


def exact_any_regex(values: list[str]) -> str:
    escaped = [str(value).replace("\\", "\\\\").replace(".", "\\.") for value in values if str(value).strip()]
    return "^(?:" + "|".join(escaped) + ")$"


def nginx_path(value: str) -> str:
    return str(value).replace("\\", "/").replace(";", "").replace("{", "").replace("}", "")


def nginx_value(value: str) -> str:
    return str(value or "").replace("\x00", "").replace(";", "").replace("{", "").replace("}", "").replace("\n", " ")


def nginx_string(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"').replace(";", "")


def nginx_comment(value: str) -> str:
    return str(value or "").replace("\n", " ").replace("\r", " ")


def safe_identifier(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", str(value or "site"))
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe[:48] or "site"


def block_page(site: dict) -> str:
    title = "Request blocked"
    message = f"FreeWAF blocked this request for {site.get('name', 'this site')}."
    return error_page_html(title, message)


def error_page_html(title: str, message: str) -> str:
    html = (
        "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{title}</title>"
        "<style>body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:#f5f7f8;color:#17202a;display:grid;min-height:100vh;place-items:center}"
        "main{width:min(560px,calc(100vw - 32px));background:#fff;border:1px solid #d8e0ea;border-radius:8px;padding:28px}"
        "h1{margin:0 0 12px;font-size:24px}p{line-height:1.55;margin:0;color:#526071}</style></head>"
        f"<body><main><h1>{title}</h1><p>{message}</p></main></body></html>"
    )
    return html.replace("\\", "\\\\").replace("'", "\\'")


def parse_int(value) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None
